<?php use GalaxiaEditor\input\InputRender;


$userEmail = (isset($_SESSION['post']['userEmail'])) ? h($_SESSION['post']['userEmail']) : '' ?>

<form action="/edit/login" method="post" autocomplete="on">

<?php   foreach ($inputs as $input) { ?>
<?php       echo InputRender::renderInput($app, $input); ?>
<?php   } ?>


    <div class="input-wrap pad">
        <div class="input-label"></div>
        <button class="btn btn-green active" type="submit">Login</button>
    </div>

</form>
