<?php
// Copyright 2017-2024 Ino Detelić & Zaloa G. Ramos (setastart.com)
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\G;
use Galaxia\Text;
use GalaxiaEditor\E;
use GalaxiaEditor\input\InputRender;


// @formatter:off
?>
<?php   InputRender::form('', 'item-edit', 'formDisable formPrevent item paper pad'); ?>

    <div class="paper-header pad">
        <h1><?=Text::st(E::$pgTitle)?></h1>

<?php   if (E::$firstStatus) { ?>
<?php       echo InputRender::status(E::$item['inputs'][E::$firstStatus]); ?>
<?php   } ?>

        <div class="paper-header-actions">
            <button type="submit" class="btn btn-green active"><?=Text::t('Save')?></button>
            <button class="btn btn-blue active" name="submitAndGoBack"><?=Text::t('Save and go back')?></button>
        </div>

        <div class="paper-header-links">
            <div>
                <a href="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$itemId)?>" class="btn-a"><?=Text::t('Reload')?></a>
<?php   if (E::$prev) { ?>
                <a href="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$prev)?>" class="btn-a">< <?=Text::t('Previous')?></a>
<?php   } ?>
<?php   if (E::$next) { ?>
                <a href="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$next)?>" class="btn-a"><?=Text::t('Next')?> ></a>
<?php   } ?>
            </div>

<?php   if (E::$item['gcVisit']) { ?>
            <div>
            <?=Text::t('Open here')?>:
<?php   } ?>

<?php   if (is_int(E::$item['gcVisit']) || E::$item['gcVisit'] === true) { ?>
<?php       foreach (G::langs() as $lang) { ?>
<?php           if (isset(E::$item['inputs']['slug_' . $lang])) { ?>
            <a rel="noreferrer" href="<?=G::addLangPrefix(E::$pageById[E::$item['gcVisit']]['slug'][$lang] . '/' . E::$item['inputs']['slug_' . $lang]['value'], $lang)?>" class="btn-a"><?=Text::h($lang)?></a>
<?php           } else if (isset(E::$item['inputs'][E::$item['gcTable'] . 'Slug_' . $lang])) { ?>
            <a rel="noreferrer" href="<?=G::addLangPrefix(E::$pageById[E::$item['gcVisit']]['slug'][$lang] . '/' . E::$item['inputs'][E::$item['gcTable'] . 'Slug_' . $lang]['value'], $lang)?>" class="btn-a"><?=Text::h($lang)?></a>
<?php           } else if (isset(E::$pageById[E::$item['gcVisit']]['slug'][$lang])) { ?>
            <a rel="noreferrer" href="<?=G::addLangPrefix(E::$pageById[E::$item['gcVisit']]['slug'][$lang], $lang)?>" class="btn-a"><?=Text::h($lang)?></a>
<?php           }  ?>
<?php       } ?>
<?php   } else if (is_array(E::$item['gcVisit'])) { ?>
<?php       foreach (E::$item['gcVisit'] as $link) { ?>
<?php           if (!isset($link['id'])) continue ?>
<?php           if (!isset($link['prefix'])) continue ?>
<?php           $id = E::$item['inputs'][$link['id']]['value'] ?? ''; ?>
<?php           $prefix = $link['prefix'] ?? ''; ?>
<?php           $name = $prefix . E::$item['inputs'][$link['id']]['value']; ?>
            <a rel="noreferrer" href="<?=Text::h($name)?>" class="btn-a"><?=Text::h($name)?></a>
<?php       } ?>
<?php   } ?>

<?php   if (E::$item['gcVisit']) { ?>
            </div>
            <div>
            <?=Text::t('Open in new tab')?>:
<?php   } ?>

<?php   if (is_int(E::$item['gcVisit']) || E::$item['gcVisit'] === true) { ?>
<?php       foreach (G::langs() as $lang) { ?>
<?php           if (isset(E::$item['inputs']['slug_' . $lang])) { ?>
            <a target="_blank" rel="noreferrer" href="<?=G::addLangPrefix(E::$pageById[E::$item['gcVisit']]['slug'][$lang] . '/' . E::$item['inputs']['slug_' . $lang]['value'], $lang)?>" class="btn-a"><?=Text::h($lang)?></a>
<?php           } else if (isset(E::$item['inputs'][E::$item['gcTable'] . 'Slug_' . $lang])) { ?>
            <a target="_blank" rel="noreferrer" href="<?=G::addLangPrefix(E::$pageById[E::$item['gcVisit']]['slug'][$lang] . '/' . E::$item['inputs'][E::$item['gcTable'] . 'Slug_' . $lang]['value'], $lang)?>" class="btn-a"><?=Text::h($lang)?></a>
<?php           } else if (isset(E::$pageById[E::$item['gcVisit']]['slug'][$lang])) { ?>
            <a target="_blank" rel="noreferrer" href="<?=G::addLangPrefix(E::$pageById[E::$item['gcVisit']]['slug'][$lang], $lang)?>" class="btn-a"><?=Text::h($lang)?></a>
<?php           } ?>
<?php       } ?>
<?php   } else if (is_array(E::$item['gcVisit'])) { ?>
<?php       foreach (E::$item['gcVisit'] as $link) { ?>
<?php           if (!isset($link['id'])) continue ?>
<?php           if (!isset($link['prefix'])) continue ?>
<?php           $id = E::$item['inputs'][$link['id']]['value'] ?? ''; ?>
<?php           $prefix = $link['prefix'] ?? ''; ?>
<?php           $name = $prefix . E::$item['inputs'][$link['id']]['value']; ?>
            <a target="_blank" rel="noreferrer" href="<?=Text::h($name)?>" class="btn-a"><?=Text::h($name)?></a>
<?php       } ?>
<?php   } ?>
<?php   if (E::$item['gcVisit']) { ?>
            </div>
<?php   } ?>
        </div>
    </div>


<?php   if (E::$item['inputs'] ?? []) { ?>
    <div class="item-row">
<?php       $firstTime = true; ?>
<?php       $prefixPrev = null; ?>
<?php       foreach (E::$item['inputs'] as $inputKey => $input) { ?>
<?php           if ($inputKey == E::$firstStatus) continue; ?>
<?php           if (!$firstTime && ($prefixPrev == null || !isset($input['prefix']) || $input['prefix'] !== $prefixPrev)) { ?>
    </div>

    <div class="item-row">
<?php           } ?>
<?php           echo InputRender::renderInput($input); ?>
<?php           $firstTime = false; ?>
<?php           $prefixPrev = $input['prefix'] ?? null; ?>
<?php       } ?>
    </div>
<?php   } ?>


<?php // @formatter:on

foreach (E::$modules as E::$moduleKey => &E::$module) {
    if (!E::$module['inputs'] ?? []) continue;
    switch (E::$module['gcModuleType']) {
        case 'fields':
            if (empty(E::$module['inputs'])) {
                $foundMulti = false;
                if (!empty(E::$module['gcModuleMultiple'])) {
                    $foundMulti = true;
                    break;
                }
                if (!$foundMulti) continue 2;
            }
            include G::$editor->dirView . 'item/modules/fields.phtml';
            break;
        default:
            G::errorPage(500, 'invalid phtml module');
            break;
    }
}

$classDel = 'red btn-a';
foreach (E::$item['gcDelete']['gcPerms'] ?? [] as $perm) {
    $classDel .= ' hide-perm-' . Text::h($perm);
}

// @formatter:off ?>


    <div class="paper-footer pad">
        <div class="item-info">
<?php   if (E::$item['gcInfo']) { ?>
<?php       foreach (E::$item['gcInfo'] as $info) { ?>
            <p><?=Text::t($info['label'])?>: <?=Text::h($info['value'])?></p>
<?php       } ?>
<?php   } ?>
            <a target="_blank" href="/edit/history/<?=Text::h(E::$item['gcTable'])?>/<?=Text::h(E::$itemId)?>" class="btn-a"><?=Text::t('Open History in a new tab')?></a>
<?php   if (G::isDev()) { ?>
            <a href="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$itemId)?>/history" class="hide-perm-dev btn-a"><?=sprintf(Text::t('Save %s in History'), Text::t(E::$section['gcTitleSingle']))?></a>
<?php   } ?>
<?php   if (E::$item['gcDelete']) { ?>
            <a href="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$itemId)?>/delete" class="<?=$classDel?>"><?=sprintf(Text::t('Delete %s'), Text::t(E::$section['gcTitleSingle']))?></a>
<?php   } ?>
        </div>
        <div class="paper-footer-actions">
            <button type="submit" class="btn btn-green active"><?=Text::t('Save')?></button>
            <button class="btn btn-blue active" name="submitAndGoBack"><?=sprintf(Text::t('Save and go back to %s'), Text::t(E::$section['gcTitlePlural']))?></button>
        </div>
    </div>

<?php   InputRender::renderFormEnd(); ?>
