<?php

use Galaxia\G;
use Galaxia\Text;
use GalaxiaEditor\E;
use GalaxiaEditor\input\InputRender;


InputRender::form('', 'item-edit', 'item paper pad'); ?>

    <div class="paper-header pad">
        <h1><?=Text::st($pgTitle)?></h1>

<?php   if ($firstStatus) { ?>
<?php       echo InputRender::status($item['inputs'][$firstStatus]); ?>
<?php   } ?>

        <div class="paper-header-actions">
            <button type="submit" class="btn btn-green active"><?=Text::t('Save')?></button>
            <button class="btn btn-blue active" name="submitAndGoBack"><?=Text::t('Save and go back')?></button>
        </div>

        <div class="paper-header-links">
            <a href="/edit/<?=Text::h($pgSlug)?>/<?=Text::h($itemId)?>" class="btn-a"><?=Text::t('Reload')?></a>
<?php   if ($item['gcVisit']) { ?>
            <br><?=Text::t('Open here')?>:
<?php   } ?>

<?php   if (is_int($item['gcVisit']) || $item['gcVisit'] === true) { ?>
<?php       foreach (G::langs() as $lang) { ?>
<?php           if (isset($item['inputs']['slug_' . $lang])) { ?>
            <a rel="noreferrer" href="<?=G::addLangPrefix($pageById[$item['gcVisit']]['slug'][$lang] . '/' . $item['inputs']['slug_' . $lang]['value'], $lang)?>" class="btn-a"><?=Text::h($lang)?></a>
<?php           } else if (isset($item['inputs'][$item['gcTable'] . 'Slug_' . $lang])) { ?>
            <a rel="noreferrer" href="<?=G::addLangPrefix($pageById[$item['gcVisit']]['slug'][$lang] . '/' . $item['inputs'][$item['gcTable'] . 'Slug_' . $lang]['value'], $lang)?>" class="btn-a"><?=Text::h($lang)?></a>
<?php           } else if (isset($pageById[$item['gcVisit']]['slug'][$lang])) { ?>
            <a rel="noreferrer" href="<?=G::addLangPrefix($pageById[$item['gcVisit']]['slug'][$lang], $lang)?>" class="btn-a"><?=Text::h($lang)?></a>
<?php           }  ?>
<?php       } ?>
<?php   } else if (is_array($item['gcVisit'])) { ?>
<?php       foreach ($item['gcVisit'] as $link) { ?>
<?php           if (!isset($link['id'])) continue ?>
<?php           if (!isset($link['prefix'])) continue ?>
<?php           $id = $item['inputs'][$link['id']]['value'] ?? ''; ?>
<?php           $prefix = $link['prefix'] ?? ''; ?>
<?php           $name = $prefix . $item['inputs'][$link['id']]['value']; ?>
            <a rel="noreferrer" href="<?=Text::h($name)?>" class="btn-a"><?=Text::h($name)?></a>
<?php       } ?>
<?php   } ?>

<?php   if ($item['gcVisit']) { ?>
            <br><?=Text::t('Open in new tab')?>:
<?php   } ?>

<?php   if (is_int($item['gcVisit']) || $item['gcVisit'] === true) { ?>
<?php       foreach (G::langs() as $lang) { ?>
<?php           if (isset($item['inputs']['slug_' . $lang])) { ?>
            <a target="_blank" rel="noreferrer" href="<?=G::addLangPrefix($pageById[$item['gcVisit']]['slug'][$lang] . '/' . $item['inputs']['slug_' . $lang]['value'], $lang)?>" class="btn-a"><?=Text::h($lang)?></a>
<?php           } else if (isset($item['inputs'][$item['gcTable'] . 'Slug_' . $lang])) { ?>
            <a target="_blank" rel="noreferrer" href="<?=G::addLangPrefix($pageById[$item['gcVisit']]['slug'][$lang] . '/' . $item['inputs'][$item['gcTable'] . 'Slug_' . $lang]['value'], $lang)?>" class="btn-a"><?=Text::h($lang)?></a>
<?php           } else if (isset($pageById[$item['gcVisit']]['slug'][$lang])) { ?>
            <a target="_blank" rel="noreferrer" href="<?=G::addLangPrefix($pageById[$item['gcVisit']]['slug'][$lang], $lang)?>" class="btn-a"><?=Text::h($lang)?></a>
<?php           } ?>
<?php       } ?>
<?php   } else if (is_array($item['gcVisit'])) { ?>
<?php       foreach ($item['gcVisit'] as $link) { ?>
<?php           if (!isset($link['id'])) continue ?>
<?php           if (!isset($link['prefix'])) continue ?>
<?php           $id = $item['inputs'][$link['id']]['value'] ?? ''; ?>
<?php           $prefix = $link['prefix'] ?? ''; ?>
<?php           $name = $prefix . $item['inputs'][$link['id']]['value']; ?>
            <a target="_blank" rel="noreferrer" href="<?=Text::h($name)?>" class="btn-a"><?=Text::h($name)?></a>
<?php       } ?>
<?php   } ?>
        </div>
    </div>


<?php   if ($item['inputs'] ?? []) { ?>
    <div class="item-row">
<?php       $firstTime = true; ?>
<?php       $prefixPrev = null; ?>
<?php       foreach ($item['inputs'] as $inputKey => $input) { ?>
<?php           if ($inputKey == $firstStatus) continue; ?>
<?php           if (!$firstTime && ($prefixPrev == null || !isset($input['prefix']) || $input['prefix'] !== $prefixPrev)) { ?>
    </div>

    <div class="item-row">
<?php           } ?>
<?php           echo InputRender::renderInput($app, $input); ?>
<?php           $firstTime = false; ?>
<?php           $prefixPrev = $input['prefix'] ?? null; ?>
<?php       } ?>
    </div>
<?php   } ?>


<?php

foreach ($modules as $moduleKey => $module) {
    if (!$module['inputs'] ?? []) continue;
    switch ($module['gcModuleType']) {
        case 'fields':
            if (empty($module['inputs'])) {
                $foundMulti = false;
                if (!empty($module['gcModuleMultiple'])) {
                    $foundMulti = true;
                    break;
                }
                if (!$foundMulti) continue 2;
            }
            include $editor->dirView . 'item/modules/fields.phtml';
            break;
        default:
            geErrorPage(500, 'invalid phtml module');
            break;
    }
}

?>


    <div class="paper-footer pad">
        <div class="item-info">
<?php   if ($item['gcInfo']) { ?>
<?php       foreach ($item['gcInfo'] as $info) { ?>
            <p><?=Text::t($info['label'])?>: <?=Text::h($info['value'])?></p>
<?php       } ?>
<?php   } ?>
            <a target="_blank" href="/edit/history/<?=Text::h($item['gcTable'])?>/<?=Text::h($itemId)?>" class="btn-a"><?=Text::t('Open History in a new tab')?></a>
<?php   if ($me->hasPerm('dev')) { ?>
            <a href="/edit/<?=Text::h($pgSlug)?>/<?=Text::h($itemId)?>/history" class="hide-perm-dev btn-a"><?=sprintf(Text::t('Save %s in History'), Text::t(E::$conf[$pgSlug]['gcTitleSingle']))?></a>
<?php   } ?>
<?php   if ($item['gcDelete']) { ?>
            <a href="/edit/<?=Text::h($pgSlug)?>/<?=Text::h($itemId)?>/delete" class="red btn-a"><?=sprintf(Text::t('Delete %s'), Text::t(E::$conf[$pgSlug]['gcTitleSingle']))?></a>
<?php   } ?>
        </div>
        <div class="paper-footer-actions">
            <button type="submit" class="btn btn-green active"><?=Text::t('Save')?></button>
            <button class="btn btn-blue active" name="submitAndGoBack"><?=sprintf(Text::t('Save and go back to %s'), Text::t(E::$conf[$pgSlug]['gcTitlePlural']))?></button>
        </div>
    </div>

<?php   InputRender::renderFormEnd(); ?>
