<?php
// Copyright 2017-2022 Ino Detelić & Zaloa G. Ramos
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// You may obtain a copy of the Licence at: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\Text;
use GalaxiaEditor\E;
use GalaxiaEditor\input\InputRender;

// @formatter:off
?>
<?php   InputRender::form('', 'image-new', 'image image-new paper pad'); ?>

    <div class="paper-header pad">
        <h1><?=Text::st(E::$pgTitle)?></h1>
    </div>

    <div class="item-row">
<?php   $firstTime = true; ?>
<?php   $prefixPrev = null; ?>
<?php   foreach (E::$imgInputs as $input) { ?>
<?php       if (!$firstTime && ($prefixPrev == null || !isset($input['prefix']) || $input['prefix'] !== $prefixPrev)) { ?>
    </div>

    <div class="item-row">
<?php       } ?>
<?php       echo InputRender::renderInput($input); ?>
<?php       $firstTime = false; ?>
<?php       $prefixPrev = $input['prefix'] ?? ''; ?>
<?php   } ?>
    </div>

    <div class="paper-footer pad">
        <div class="item-info">
<?php   if (isset($item['gcInfo'])) { ?>
<?php       foreach ($item['gcInfo'] as $info) { ?>
            <p><?=Text::t($info['label'])?>: <?=Text::h($info['value'])?></p>
<?php       } ?>
<?php   } ?>
        </div>
        <div class="paper-footer-actions">
            <button class="btn btn-green active"><?=Text::t('Upload')?></button>
            <button class="btn btn-aqua active" name="submitAndGoBack"><?=sprintf(Text::t('Upload and go back to %s'), Text::t(E::$section['gcTitlePlural']))?></button>
            <button class="btn btn-aqua active" name="submitAndAddMore"><?=Text::t('Upload these and more')?></button>
        </div>
    </div>

<?php   InputRender::renderFormEnd(); ?>
