<?php
// Copyright 2017-2022 Ino Detelić & Zaloa G. Ramos
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\Text;
use GalaxiaEditor\E;


// @formatter:off
?>
<div class="history">
    <div class="item-title">
        <h1><?=Text::st(E::$pgTitle)?></h1>
    </div>
<?php   if (isset(E::$historyRootSlugs[E::$tabName])) { ?>
    <div class="paper-header">
        <a href="/edit/<?=Text::h(E::$historyRootSlugs[E::$tabName])?>/<?=Text::h(E::$tabId)?>"><?=Text::t('Edit Item')?></a>
    </div>
<?php   } ?>
<?php   foreach (E::$historyItems as $itemId => $item) { ?>
    <div id="<?=Text::h($itemId)?>" class="history-item paper pad action-<?=Text::h($item['action'])?>">
<?php       foreach ($item['changes'] as $change) { ?>
        <div class="input-label pad"><span class="input-label-lang"><?=Text::t($change['lang'])?></span> <?=Text::t($change['name'])?></div>
        <div class="content pad"><?=strip_tags($change['content'], Text::ALLOWED_TAGS)?></div>
<?php       } ?>
        <div class="paper-footer">
            <p class="pad"><?=Text::t('action-' . $item['action'])?>: <?=Text::formatDate($item['created'], 'd MMM y - HH:mm')?></p>
            <p class="grey pad"><?=Text::t('Id')?>: <?=Text::h($itemId)?></p>
        </div>
    </div>
<?php   } ?>

</div>
