<?php

use Galaxia\Text;


?>
<div class="history">
    <div class="item-title">
        <h1><?=Text::st($pgTitle)?></h1>
    </div>
<?php   if (isset($rootSlugs[$tabName])) { ?>
    <div class="paper-header">
        <a href="/edit/<?=Text::h($rootSlugs[$tabName])?>/<?=Text::h($tabId)?>"><?=Text::t('Edit Item')?></a>
    </div>
<?php   } ?>
<?php   foreach ($items as $itemId => $item) { ?>
    <div id="<?=Text::h($itemId)?>" class="history-item paper pad action-<?=Text::h($item['action'])?>">
<?php       foreach ($item['changes'] as $change) { ?>
        <div class="input-label pad"><span class="input-label-lang"><?=Text::t($change['lang'])?></span> <?=Text::t($change['name'])?></div>
        <div class="content pad"><?=strip_tags($change['content'], Text::ALLOWED_TAGS)?></div>
<?php       } ?>
        <div class="paper-footer">
            <p class="pad"><?=Text::t('action-' . $item['action'])?>: <?=Text::formatDate($item['created'], 'd MMM y - HH:mm')?></p>
            <p class="grey pad"><?=Text::t('Id')?>: <?=Text::h($itemId)?></p>
        </div>
    </div>
<?php   } ?>

</div>
