<?php

use Galaxia\G;
use Galaxia\Text;
use GalaxiaEditor\E;
use GalaxiaEditor\input\InputRender;
use GalaxiaEditor\render\view\ViewPagination;


InputRender::form('', 'history-list', 'paper pad');?>

    <div class="paper-header">
        <h1 class="pad"><span class="nrFiltered"><?=Text::h(E::$pagination->itemsFiltered)?></span> &#8725; <?=Text::h(E::$pagination->itemsTotal)?> <?=Text::t(E::$pgTitle);?></h1>
    </div>


<?php ViewPagination::renderHeader(E::$pagination) ?>


    <div class="load">
<?php   include G::$editor->dirView . 'history/results.phtml'; ?>
    </div>


<?php ViewPagination::renderFooter(E::$pagination) ?>


<?php   InputRender::renderFormEnd(); ?>

