<?php
// Copyright 2017-2022 Ino Detelić & Zaloa G. Ramos
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\G;
use Galaxia\Text;
use GalaxiaEditor\E;
use GalaxiaEditor\input\InputRender;
use GalaxiaEditor\frag\FragPagination;

// @formatter:off
?>
<?php   InputRender::form('', 'history-list', 'paper pad');?>

    <div class="paper-header">
        <h1 class="pad"><span class="nrFiltered"><?=Text::h(E::$pagination->itemsFiltered)?></span> &#8725; <?=Text::h(E::$pagination->itemsTotal)?> <?=Text::t(E::$pgTitle);?></h1>
    </div>


<?php   FragPagination::renderHeader(E::$pagination) ?>


    <div class="load">
<?php   include G::$editor->dirView . 'history/results.phtml'; ?>
    </div>


<?php   FragPagination::renderFooter(E::$pagination) ?>


<?php   InputRender::renderFormEnd(); ?>
