<?php use Galaxia\Text;
use GalaxiaEditor\input\InputRender;
use GalaxiaEditor\render\view\ViewPagination;


InputRender::form('', 'history-list', 'paper pad');?>

    <div class="paper-header">
        <h1 class="pad"><span class="nrFiltered"><?=Text::h($rowsTotal)?></span> &#8725; <?=Text::h($rowsTotal)?> <?=Text::t($pgTitle);?></h1>
    </div>


<?php ViewPagination::renderHeader($pagination) ?>


    <div class="load">
<?php   include $editor->dirView . 'history/results.phtml'; ?>
    </div>


<?php ViewPagination::renderFooter($pagination) ?>


<?php   InputRender::renderFormEnd(); ?>

