<?php   renderForm('', 'image-delete', 'image image-delete paper pad'); ?>

    <div class="paper-header pad">
        <h1><?=h($pgTitle)?></h1>
        <div class="paper-header-links">
            <a href="/edit/<?=h($pgSlug)?>/<?=h($imgSlug)?>" class="btn-a"><?=t('Go back')?></a>
        </div>
    </div>

    <div class="image-preview pad">
        <figure>
            <?=gImageRender($img), PHP_EOL?>
        </figure>
    </div>

    <div class="paper-footer pad">
<?php   include $editor->dirView . 'image/fragment/paper-footer-info.phtml'; ?>
        <div class="paper-footer-actions">
            <a class="btn btn-blue btn-mb active" href="/edit/<?=h($pgSlug)?>/<?=h($imgSlug)?>"><?=t('Cancel')?></a>
            <button class="btn btn-red btn-mb active"><?=sprintf(t('Delete %s'), t($geConf[$pgSlug]['gcTitleSingle']))?></button>
        </div>
    </div>

<?php   renderFormEnd(); ?>
