<div class="paper pad">

    <div class="paper-header pad">
        <h1><?=t($pgTitle);?></h1>
    </div>

    <div class="gchat-room pad" data-room="/edit/chat">
        <div class="title"><?=t($pgTitle);?></div>
        <div class="users"></div>
        <div class="messages-wrapper">
            <div class="s0w s1w messages">
            </div>
        </div>
        publish status: <span class="status-publish"></span>
        <div class="send input-wrap input-wrap-textarea">
            <div class="input-label">
                <?=t('Send message')?><br>
            </div>
            <textarea class="input-text input-textarea rl" name="msg" rows="1" oninput="textareaAutoGrow(this)" onkeydown="gjcEnterSend(this, event, '/edit/chat')" wrap="soft"></textarea>
            <button class="btn btn-green active rr" onclick="gjcClickSend(this, '/edit/chat')"><?=t('Send')?></button>
        </div>
    </div>

    listen status: <span id="status-listen"></span>

</div>
