<?php
// Copyright 2017-2023 Ino Detelić & Zaloa G. Ramos (setastart.com)
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\Text;
use GalaxiaEditor\E;
use GalaxiaEditor\input\InputRender;


// @formatter:off
?>
<div id="module-<?=E::$moduleKey?>" class="module">
<?php   if (E::$module['gcModuleTitle']) { ?>
    <h2 class="pad"><?=Text::t(E::$module['gcModuleTitle'])?></h2>
<?php   } ?>
<?php   foreach (E::$module['inputs'] as $fieldKey => $fields) {

            $moduleFieldCss = 'module-field';
            $multi = $reorder = $unique = false;
            $gallery = false;
            if (isset(E::$module['gcModuleMultiple'][$fieldKey])) {
                $multi = true;
                $reorder = E::$module['gcModuleMultiple'][$fieldKey]['reorder'];
                $unique = E::$module['gcModuleMultiple'][$fieldKey]['unique'];
                $gallery = E::$module['gcModuleMultiple'][$fieldKey]['gallery'] ?? false;
                $moduleFieldCss .= ' module-field-multi';
                if ($gallery) $moduleFieldCss .= ' module-field-gallery';
            }

            $modKeyField = 'module-' . E::$moduleKey . '-' . $fieldKey;
            $modKeyFieldArr = 'modules[' . E::$moduleKey . '][' . $fieldKey . ']';
?>
<?php
            if ($multi) {
?>
    <div id="<?=$modKeyField?>-header" class="module-field-multi-header pad" data-target="<?=$modKeyField?>">
        <h2><?=Text::t(E::$module['gcModuleMultiple'][$fieldKey]['label'] ?? $fieldKey)?>: <span class="module-field-count"><?=count($fields) - 2?></span></h2>
<?php               if ($gallery) { ?>
        <div class="btn-group">
            <button type="button" class="ev-gallery-delete-none btn-new btn-new-text active" id="empty-<?=$modKeyField?>"><?=Text::t('Remove None')?></button>
            <button type="button" class="ev-gallery-delete-all btn-new btn-new-text active" id="empty-<?=$modKeyField?>"><?=Text::t('Remove All')?></button>
        </div>
        <div class="btn-group">
            <button type="button" class="ev-gallery-reorder btn-new btn-new-text active" id="reorder-<?=$modKeyField?>"><?=Text::t('Reorder Images')?></button>
        </div>
        <div class="btn-group">
            <button type="button" class="ev-gallery-add btn-new btn-new-plus-text active" id="add-<?=$modKeyField?>-new"><?=Text::t('Add')?></button>
        </div>
<?php               } else { ?>
        <div class="btn-group">
            <button type="button" class="ev-module-add btn-new btn-new-plus-text active" id="add-<?=$modKeyField?>-new" data-target="<?=$modKeyField?>-new" data-where="<?=$modKeyField?>" data-pos="0"><?=Text::t('Add')?></button>
        </div>
<?php               } ?>
        <div id="<?=$modKeyField?>-new" class="module-field-group hide">
            <div class="item-row">
<?php           $firstTime = true; ?>
<?php           $prefixPrev = null; ?>
<?php           foreach ($fields['new-0'] as $inputKey => $input) { ?>
<?php               if ($inputKey == 'delete' || $inputKey == 'position') continue; ?>
<?php               if (!$firstTime && ($prefixPrev == null || !isset($input['prefix']) || $input['prefix'] !== $prefixPrev)) { ?>
            </div>
            <div class="item-row">
<?php               } ?>
<?php               $input['rico-new'] = true; ?>
<?php               echo InputRender::renderInput($input); ?>
<?php               $firstTime = false; ?>
<?php               $prefixPrev = $input['prefix'] ?? null; ?>
<?php           } ?>
            </div>
            <div class="module-field-group-footer btn-row pad">
                <div class="btn-group">
                    <button title="<?=Text::t("Remove")?>" disabled type="button" class="ev-module-rem module-field-btn-delete btn-new btn-new-x active rc" data-target="<?=$modKeyField?>-new"></button>
                    <input disabled class="hide" type="checkbox" name="<?=$modKeyFieldArr?>[new-0][delete]">
                </div>
<?php           if ($reorder) { ?>
                <div class="btn-group">
                    <button title="<?=Text::t("First")?>" disabled type="button" class="ev-module-first btn-new reorder-first active" data-target="<?=$modKeyField?>-new"></button>
                    <button title="<?=Text::t("Previous")?>" disabled type="button" class="ev-module-up btn-new reorder-prev active" data-target="<?=$modKeyField?>-new"></button>
                </div>
                <div class="btn-group">
                    <input disabled class="module-position input-text" type="text" min="1" name="<?=$modKeyFieldArr?>[new-0][position]" value="1">
                    <button disabled type="button" class="ev-module-go btn-new active" data-target="<?=$modKeyField?>-new">go!</button>
                </div>
                <div class="btn-group">
                    <button title="<?=Text::t("Next")?>" disabled type="button" class="ev-module-down btn-new reorder-next active" data-target="<?=$modKeyField?>-new"></button>
                    <button title="<?=Text::t("Last")?>" disabled type="button" class="ev-module-last btn-new reorder-last active" data-target="<?=$modKeyField?>-new"></button>
                </div>
<?php           } ?>
            </div>
<?php               if ($gallery) { ?>
            <div class="btn-group">
                <button title="<?=Text::t('Add')?>" type="button" class="ev-gallery-add before btn-new btn-new-plus active"></button>
            </div>
            <div class="btn-group">
                <button title="<?=Text::t('Add')?>" type="button" class="ev-gallery-add after btn-new btn-new-plus active"></button>
            </div>
<?php               } ?>
        </div>
    </div>
<?php       } ?>
    <div id="<?=$modKeyField?>" class="<?=($moduleFieldCss)?>">
<?php       foreach ($fields as $fieldVal => $field) {
                if ($fieldVal == 'proto') continue;
                $moduleGroupCss = '';
                $deleteChecked = false;
                if ($multi) {
                    $moduleGroupCss .= 'module-field-group';
                    if ($fieldVal == 'new-0') continue;
                    if (str_starts_with($fieldVal, 'new-')) {
                        $moduleGroupCss .= ' module-field-group-new';
                    }
                    if (isset($field['delete']) && $field['delete'] == 'on') {
                        $deleteChecked = true;
                        $moduleGroupCss .= ' module-field-group-delete';
                    }
                }

                $modKeyFieldVal = 'module-' . E::$moduleKey . '-' . $fieldKey . '-' . $fieldVal;
                $modKeyFieldValArr = 'modules[' . E::$moduleKey . '][' . $fieldKey . '][' . $fieldVal . ']';

?>
        <div id="<?=$modKeyFieldVal?>" class="<?=($moduleGroupCss)?>"<?=($deleteChecked) ? ' data-disabled="true"' : ''?>>
            <div class="item-row">
<?php           $firstTime = true; ?>
<?php           $prefixPrev = null; ?>
<?php           foreach ($field as $inputKey => $input) { ?>
<?php               if ($inputKey == 'delete' || $inputKey == 'position') continue; ?>
<?php               if ($deleteChecked) $input['disabled'] = true; ?>
<?php               if (!$firstTime && ($prefixPrev == null || !isset($input['prefix']) || $input['prefix'] !== $prefixPrev)) { ?>
            </div>
            <div class="item-row">
<?php               } ?>
<?php               echo InputRender::renderInput($input); ?>
<?php               $firstTime = false; ?>
<?php               $prefixPrev = $input['prefix'] ?? null; ?>
<?php           } ?>
            </div>
<?php           if ($multi) { ?>
            <div class="module-field-group-footer btn-row pad">
                <div class="btn-group">
                    <button title="<?=Text::t("Remove")?>" type="button" class="ev-module-rem module-field-btn-delete btn-new btn-new-x active rc" data-target="<?=$modKeyFieldVal?>"></button>
                    <input class="hide" type="checkbox" name="<?=$modKeyFieldValArr?>[delete]"<?=($deleteChecked) ? ' checked' : ''?>>
                </div>
<?php               if ($reorder) { ?>
                <div class="btn-group">
                    <button title="<?=Text::t("First")?>" type="button" class="ev-module-first btn-new reorder-first active" data-target="<?=$modKeyFieldVal?>"<?=($deleteChecked) ? ' disabled' : ''?>></button>
                    <button title="<?=Text::t("Previous")?>" type="button" class="ev-module-up btn-new reorder-prev active" data-target="<?=$modKeyFieldVal?>"<?=($deleteChecked) ? ' disabled' : ''?>></button>
                </div>
                <div class="btn-group">
                    <input class="module-position input-text" type="text" min="1" name="<?=$modKeyFieldValArr?>[position]" value="<?=$field['position']?>"<?=($deleteChecked) ? ' disabled' : ''?>>
                    <button type="button" class="ev-module-go btn-new active" data-target="<?=$modKeyFieldVal?>"<?=($deleteChecked) ? ' disabled' : ''?>>go!</button>
                </div>
                <div class="btn-group">
                    <button title="<?=Text::t("Next")?>" type="button" class="ev-module-down btn-new reorder-next active" data-target="<?=$modKeyFieldVal?>"<?=($deleteChecked) ? ' disabled' : ''?>></button>
                    <button title="<?=Text::t("Last")?>" type="button" class="ev-module-last btn-new reorder-last active" data-target="<?=$modKeyFieldVal?>"<?=($deleteChecked) ? ' disabled' : ''?>></button>
                </div>
<?php               } ?>
            </div>
<?php               if ($gallery) { ?>
            <div class="btn-group">
                <button title="<?=Text::t('Add')?>" type="button" class="ev-gallery-add before btn-new btn-new-plus active"></button>
            </div>
            <div class="btn-group">
                <button title="<?=Text::t('Add')?>" type="button" class="ev-gallery-add after btn-new btn-new-plus active"></button>
            </div>
<?php               } ?>
<?php           } ?>
        </div>
<?php       } ?>
    </div>
<?php   } ?>
</div>
