<?php
// Copyright 2017-2024 Ino Detelić & Zaloa G. Ramos (setastart.com)
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\Text;
use GalaxiaEditor\E;
use GalaxiaEditor\input\InputRender;

// @formatter:off
?>
<?php   InputRender::form('', 'item-new', 'formPrevent item item-new paper pad'); ?>

    <div class="paper-header pad">
        <h1><?=Text::st(E::$pgTitle)?></h1>

<?php   if (isset(E::$item['inputs']['status'])) { ?>
<?php       echo InputRender::status(E::$item['inputs']['status']); ?>
<?php   } ?>
    </div>


    <div class="item-row">
<?php   $firstTime = true; ?>
<?php   $prefixPrev = null; ?>
<?php   foreach (E::$item['inputs'] as $input) { ?>
<?php       if ($input['nameFromDb'] == 'status') continue; ?>
<?php       if (!$firstTime && ($prefixPrev == null || !isset($input['prefix']) || $input['prefix'] !== $prefixPrev)) { ?>
    </div>
    <div class="item-row">
<?php       } ?>
<?php       echo InputRender::renderInput($input); ?>
<?php       $firstTime = false; ?>
<?php       $prefixPrev = $input['prefix'] ?? ''; ?>
<?php   } ?>
    </div>


    <div class="paper-footer pad">
        <div class="paper-footer-actions">
            <button class="btn btn-green active"><?=Text::t('Save')?></button>
            <button class="btn btn-blue active" name="submitAndGoBack"><?=sprintf(Text::t('Save and go back to %s'), Text::t(E::$section['gcTitlePlural']))?></button>
            <button class="btn btn-blue active" name="submitAndAddMore"><?=Text::t('Save and add more')?></button>
        </div>
    </div>

<?php   InputRender::renderFormEnd(); ?>
