<?php

use Galaxia\G;
use Galaxia\Text;
use GalaxiaEditor\input\InputRender;


InputRender::form('', 'image-replace', 'image image-new paper pad'); ?>

    <div class="paper-header pad">
        <h1><?=Text::st($pgTitle)?></h1>
        <div class="paper-header-links">
            <a href="/edit/<?=Text::h($pgSlug)?>/<?=Text::h($imgSlug)?>" class="btn-a"><?=Text::t('Go back')?></a>
        </div>
    </div>

    <div class="item-row">
<?php   $firstTime = true; ?>
<?php   $prefixPrev = null; ?>
<?php   foreach ($inputs as $input) { ?>
<?php       if (!$firstTime && ($prefixPrev == null || !isset($input['prefix']) || $input['prefix'] !== $prefixPrev)) { ?>
    </div>

    <div class="item-row">
<?php       } ?>
<?php       echo InputRender::renderInput($app, $input); ?>
<?php       $firstTime = false; ?>
<?php       $prefixPrev = $input['prefix'] ?? ''; ?>
<?php   } ?>
    </div>

    <div class="image-preview pad">
        <figure>
            <?=G::image($img), PHP_EOL?>
        </figure>
    </div>

    <div class="paper-footer pad">
<?php   include $editor->dirView . 'image/fragment/paper-footer-info.phtml'; ?>
        <div class="paper-footer-actions pad">
            <button class="btn btn-green active"><?=Text::t('Replace')?></button>
        </div>
    </div>

<?php   InputRender::renderFormEnd(); ?>
