<?php

use Galaxia\Text;
use GalaxiaEditor\input\InputRender;


InputRender::form('', 'image-delete', 'image image-delete paper pad'); ?>

<div class="paper-header pad">
    <h1><?=Text::st($pgTitle)?></h1>
</div>

<div id="imageDelete-header" class="module-field-multi-header pad" data-target="imageDelete">
    <h2><?=Text::t('Images to Delete')?>: <span class="module-field-count">0</span></h2>
    <div class="btn-group">
        <button type="button" class="ev-gallery-delete-all btn-new btn-new-text active" id="empty-imageDelete">Borrar Todas</button>
    </div>
    <div class="btn-group">
        <button type="button" class="ev-gallery-add btn-new btn-new-plus-text active" id="add-imageDelete-new">Añadir</button>
    </div>
    <div id="imageDelete-new" class="module-field-group hide">
        <div class="item-row">
            <div class="input-wrap input-wrap-slugImage pad ">
                <div class="input-label"><span class="input-title" title="">Imágenes</span></div>
                <textarea pattern="[a-z0-9\-]*" class="input-text input-slug input-slugImg" name="modules[0][imageDelete][new-0][imgSlug]" rows="1" wrap="soft" disabled></textarea>
                <button type="button" class="slugImage figure empty" data-imgtype="">
                    <img alt="" src="/edit/gfx/no-photo-add.png">
                </button>
            </div>
        </div>
        <div class="module-field-group-footer btn-row pad">
            <div class="btn-group">
                <button title="Remover" disabled="" type="button" class="ev-module-rem module-field-btn-delete btn-new btn-new-x active rc"
                        data-target="imageDelete-new"></button>
                <input disabled="" class="hide" type="checkbox" name="modules[0][imageDelete][new-0][delete]">
            </div>
        </div>
    </div>
</div>

<div id="imageDelete" class="module-field module-field-multi module-field-gallery imageDelete">
</div>

<div class="paper-footer pad">
    <div class="paper-footer-actions">
        <a class="btn btn-blue btn-mb active" href="/edit/<?=Text::h($pgSlug)?>"><?=Text::t('Cancel')?></a>
        <button class="btn btn-red btn-mb active"><?=sprintf(Text::t('Delete %s'), Text::t($geConf[$pgSlug]['gcTitlePlural']))?></button>
    </div>
</div>

<?php InputRender::renderFormEnd(); ?>
