<?php use Galaxia\Text;
use GalaxiaEditor\input\InputRender;
use GalaxiaEditor\render\view\ViewPagination;


InputRender::form('', 'image-list', 'paper pad');?>

    <div class="paper-header pad">
        <h1><span class="rowsFiltered"><?=Text::h($rowsFiltered)?></span> &#8725; <span class="rowsTotal"><?=Text::h($rowsTotal)?></span> <?=Text::t($pgTitle);?></h1>

        <div class="list-links">
<?php   if ($geConf[$pgSlug]['gcImage']['gcDelete'] ?? []) { ?>
            <a href="/edit/<?=Text::h($pgSlug)?>/delete" class="btn btn-pad btn-red active"><?=Text::t('Delete Images')?></a>
<?php   } ?>
<?php   if ($geConf[$pgSlug]['gcImage']['gcInsert'] ?? []) { ?>
            <a href="/edit/<?=Text::h($pgSlug)?>/new" class="btn btn-pad btn-blue active"><?=Text::t('Upload Images')?></a>
<?php   } ?>
        </div>

<?php   if ($me->hasPerm('dev')) { ?>
        <div class="paper-header-links">
            <a href="/edit/dev/imageListDeleteResizes" class="hide-perm-dev btn-a"><?=Text::t('Delete Resizes')?></a>
            <a href="/edit/dev/imageListReorder" class="hide-perm-dev btn-a"><?=Text::t('Reorder Images')?></a>
        </div>
<?php   } ?>
    </div>




    <div class="filters filters-list">
<?php   if (!empty($filterTexts)) { ?>
<?php       foreach ($filterTexts as $filterId => $filter) { ?>
        <div class="input-wrap pad">
            <div class="input-label"><?=Text::t($filter['label'])?></div>
<?php           if (empty($filter['filterEmpty'])) { ?>
            <input name="filterTexts[<?=$filterId?>]" class="input-text input-filter-text input-search br" type="search" value="<?=Text::h($_POST['filterTexts'][$filterId] ?? '')?>">
<?php           } else { ?>
            <input name="filterTexts[<?=$filterId?>]" class="input-text input-filter-text input-search rl" type="search" value="<?=Text::h($_POST['filterTexts'][$filterId] ?? '')?>">
            <label for="<?=Text::h($filterId)?>-empty" class="btn btn-pill btn-checkbox rr">
                <?=Text::t('Empty')?>
                <input class="filterChangeEmpty" type="checkbox" name="filterTexts[<?=$filterId?>]" value="{{empty}}" id="<?=Text::h($filterId)?>-empty" title="<?=Text::t('Empty')?>">
            </label>
<?php           } ?>
<?php           if ($filterId == 'type') { ?>
            <p class="small"><?=implode(', ', array_map(array("\Galaxia\Text", "t"), array_filter(array_keys($geConf[$editor->imageSlug]['gcImageTypes']))))?></p>
<?php           } ?>
        </div>
<?php       } ?>
<?php   } ?>

<?php   if (!empty($filterInts)) { ?>
<?php       foreach ($filterInts as $filterId => $filter) { ?>
        <div class="input-wrap input-filter-int pad">
            <div class="input-label"><?=Text::t($filter['label'])?></div>
<?php       foreach ($filter['options'] as $key => $options) { ?>
            <label for="<?=Text::h($filterId)?>-<?=Text::h($key)?>" class="btn btn-pill btn-checkbox <?=Text::h($options['cssClass'])?><?=($options['checked']) ? ' active' : ''?>">
                <?=Text::t($options['label'])?>
                <input class="filterChange" name="filterInts[<?=$filterId?>][<?=Text::h($key)?>]" type="checkbox" value="1" id="<?=Text::h($filterId)?>-<?=Text::h($key)?>" title="<?=Text::t($options['label'])?>" <?=($options['checked']) ? ' checked' : ''?>>
            </label>
<?php       } ?>
        </div>
<?php       } ?>
<?php   } ?>
    </div>


<?php ViewPagination::renderHeader($pagination) ?>


    <div class="load">
<?php   include $editor->dirView . 'imageList/results.phtml'; ?>
    </div>


<?php ViewPagination::renderFooter($pagination) ?>


<?php   InputRender::renderFormEnd(); ?>
