<?php
// Copyright 2017-2022 Ino Detelić & Zaloa G. Ramos
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\Text;
use GalaxiaEditor\E;
use GalaxiaEditor\frag\FragPagination;


FragPagination::renderHiddenData(E::$pagination) ?>

<?php
$yearMonthPrev = '';
foreach (E::$imgRows as $imgSlug => $html) {
    $mtime     = E::$imgItems[$imgSlug]['mtime'];
    $yearMonth = date('Ym', $mtime);
    if ($yearMonth != $yearMonthPrev) {
        echo '<h2>' . Text::formatDate($mtime, 'MMMM y') . '</h2>' . PHP_EOL;
        $yearMonthPrev = $yearMonth;
    }
    echo $html;
}
?>
