<?php

use Galaxia\G;
use Galaxia\Pagination;
use Galaxia\Text;
use GalaxiaEditor\E;
use GalaxiaEditor\input\InputRender;
use GalaxiaEditor\render\view\ViewPagination;



if (!isset($filterTexts)) {
    $filterTexts = [
        'slug' => [
            'label'       => 'Filter Slugs',
            'filterEmpty' => false,
        ],
        'alt' => [
            'label'       => 'Filter Alt',
            'filterEmpty' => true,
        ],
        'inuse' => [
            'label'       => 'Filter In Use',
            'filterEmpty' => true,
        ],
        'type' => [
            'label'       => 'Filter Types',
            'filterEmpty' => true,
        ],
    ];
}

// @formatter:off
?>
<?php   InputRender::form('/edit/' . G::$editor->imageSlug, 'image-select', 'hide');?>

    <div class="image-select-header pad">
        <h1><?=Text::t('Add Images')?> <span class="rowsFiltered">0</span> &#8725; <span class="rowsTotal">0</span></h1>
        <div class="btn-group">
            <button type="button" class="btn-new btn-new-x-text rc image-select-header-close"><?=Text::t('Cancel')?></button>
        </div>
        <div class="btn-group btn-group-gallery">
            <button type="button" class="btn-new btn-new-text rc image-select-header-select-all"><?=Text::t('Select All')?></button>
        </div>
        <div class="btn-group btn-group-gallery">
            <button type="button" class="btn-new btn-new-text rc image-select-header-select-none"><?=Text::t('Deselect All')?></button>
        </div>
        <div class="btn-group btn-group-gallery">
            <button type="button" class="btn-new btn-new-check-text rc image-select-header-select"><?=Text::t('Add')?></button>
        </div>
    </div>


    <div class="filters filters-list">
        <input type="hidden" name="imageListType" value="image-select">
<?php   if (!empty($filterTexts)) { ?>
<?php       foreach ($filterTexts as $filterId => $filter) { ?>
        <div class="input-wrap pad">
            <div class="input-label"><div><?=Text::t($filter['label'])?></div></div>
            <div class="input-inputs">
<?php           if (empty($filter['filterEmpty'])) { ?>
                <input name="filterTexts[<?=$filterId?>]" class="input-text input-filter-text input-search br" type="search" value="<?=Text::h($_POST['filterTexts'][$filterId] ?? '')?>">
<?php           } else { ?>
                <input name="filterTexts[<?=$filterId?>]" class="input-text input-filter-text input-search rl" type="search" value="<?=Text::h($_POST['filterTexts'][$filterId] ?? '')?>">
                <label for="<?=Text::h($filterId)?>-empty" class="btn btn-pill btn-checkbox rr">
                    <?=Text::t('Empty')?>
                    <input class="filterChangeEmpty" type="checkbox" name="filterTexts[<?=$filterId?>]" value="{{empty}}" id="<?=Text::h($filterId)?>-empty" title="<?=Text::t('Empty')?>">
                </label>
<?php           } ?>
            </div>
<?php           if ($filterId == 'type') { ?>
                <div class="input-footer"><?=implode(', ', array_map(['\Galaxia\Text', 't'], array_filter(array_keys(E::$conf[G::$editor->imageSlug]['gcImageTypes']))))?></div>
<?php           } ?>
        </div>
<?php       } ?>
<?php   } ?>
    </div>


<?php   $pagination = new Pagination(1, 100); ?>
<?php   $pagination->setItemCounts(200); ?>
<?php ViewPagination::renderHeader($pagination) ?>


    <div id="imageSelector" class="load">
    </div>


<?php ViewPagination::renderFooter($pagination) ?>

<?php   InputRender::renderFormEnd(); ?>
