<?php use Galaxia\Text;
use GalaxiaEditor\render\view\ViewPagination;


ViewPagination::renderHiddenData($pagination, $rowsFiltered, $rowsTotal) ?>

<?php
$yearMonthPrev = '';
foreach ($rows as $imgSlug => $html) {
    $mtime = $items[$imgSlug]['mtime'];
    $yearMonth = date('Ym', $mtime);
    if ($yearMonth != $yearMonthPrev) {
        echo '<h2>' . Text::formatDate($mtime, 'MMMM y') . '</h2>' . PHP_EOL;
        $yearMonthPrev = $yearMonth;
    }
    echo $html;
}
?>

