<?php use Galaxia\Text;
use GalaxiaEditor\input\InputRender;


InputRender::form('', 'item-list', 'paper pad');?>

    <div class="paper-header pad">
        <h1><span class="rowsFiltered"><?=Text::h($rowsFiltered)?></span> &#8725; <span class="rowsTotal"><?=Text::h($rowsTotal)?></span> <?=Text::t($pgTitle);?></h1>

        <div class="list-links">
            <div class="rgt">
<?php   foreach ($list['gcLinks'] as $href => $link) { ?>
<?php       if (!$link) continue; ?>
<?php       switch ($href) { ?>
<?php           case 'new': ?>
            <a href="/edit/<?=Text::h($pgSlug)?>/<?=Text::h($href)?>" class="btn btn-pad <?=Text::h($link['cssClass'])?>"><?=sprintf(Text::t('+ Add new %s'), Text::t($geConf[$pgSlug]['gcTitleSingle']))?></a>
<?php           break; ?>
<?php           default: ?>
            <a href="/edit/<?=Text::h($pgSlug)?>/<?=Text::h($href)?>" class="btn btn-pad <?=Text::h($link['cssClass'])?>"><?=Text::t($link['label'])?></a>
<?php           break; ?>
<?php       } ?>
<?php   } ?>
            </div>
        </div>
    </div>

    <div class="filters filters-list">
<?php   if (!empty($filterTexts)) { ?>
<?php       foreach ($filterTexts as $filterId => $filter) { ?>
        <div class="input-wrap pad">
            <div class="input-label"><?=Text::t($filter['label'])?></div>
<?php           if (empty($filter['filterEmpty'])) { ?>
            <input name="filterTexts[<?=$filterId?>]" class="input-text input-filter-text input-search br" type="search" value="<?=Text::h($_POST['filterTexts'][$filterId] ?? '')?>">
<?php           } else { ?>
            <input name="filterTexts[<?=$filterId?>]" class="input-text input-filter-text input-search rl" type="search" value="<?=Text::h($_POST['filterTexts'][$filterId] ?? '')?>">
            <label for="<?=Text::h($filterId)?>-empty" class="btn btn-pill btn-checkbox rr">
                <?=Text::t('Empty')?>
                <input class="filterChangeEmpty" type="checkbox" name="filterTexts[<?=$filterId?>]" value="{{empty}}" id="<?=Text::h($filterId)?>-empty" title="<?=Text::t('Empty')?>">
            </label>
<?php           } ?>
        </div>
<?php       } ?>
<?php   } ?>

<?php   if (!empty($filterInts)) { ?>
<?php       foreach ($filterInts as $filterId => $filter) { ?>
        <div class="input-wrap input-filter-int pad">
            <div class="input-label"><?=Text::t($filter['label'])?></div>
<?php       foreach ($filter['options'] as $key => $options) { ?>
            <label for="<?=Text::h($filterId)?>-<?=Text::h($key)?>" class="btn btn-pill btn-checkbox <?=Text::h($options['cssClass'])?><?=($options['checked']) ? ' active' : ''?>">
                <?=Text::t($options['label'])?>
                <input class="filterChange" name="filterInts[<?=$filterId?>][<?=Text::h($key)?>]" type="checkbox" value="1" id="<?=Text::h($filterId)?>-<?=Text::h($key)?>" title="<?=Text::t($options['label'])?>" <?=($options['checked']) ? ' checked' : ''?>>
            </label>
<?php       } ?>
        </div>
<?php       } ?>
<?php   } ?>
    </div>


<?php   renderPaginationHeader($pagination) ?>


    <div class="load">
<?php   include $editor->dirView . 'list/results.phtml'; ?>
    </div>


<?php   renderPaginationFooter($pagination) ?>


<?php   InputRender::renderFormEnd(); ?>
