<?php
// Copyright 2017-2022 Ino Detelić & Zaloa G. Ramos
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// You may obtain a copy of the Licence at: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\G;
use Galaxia\Text;
use GalaxiaEditor\E;


// @formatter:off
?>
<div id="dev" class="paper pad">

    <div class="paper-header pad">
        <h1><?=Text::t(E::$pgTitle);?></h1>
    </div>

    <div class="dev-actions pad">
<?php   if (G::$app->cookieDebugKey && G::$app->cookieDebugVal)  { ?>
        <div><button class="btn btn-pad btn-blue active ev-cookie-set" data-key="<?=Text::h(G::$app->cookieDebugKey)?>" data-val="<?=Text::h(G::$app->cookieDebugVal)?>"><?=Text::t("Set debug cookie")?></button></div>
        <div><button class="btn btn-pad btn-blue active ev-cookie-del" data-key="<?=Text::h(G::$app->cookieDebugKey)?>"><?=Text::t("remove debug cookie")?></button></div>
<?php   } ?>
        <a href="/edit/dev/info">PHP Information</a>
        <a href="/edit/dev/sitemap">Regenerate Sitemap</a>
        <a href="/edit/dev/urls">Urls</a>
        <a href="/edit/dev/opcache">OPcache Status</a>
        <a href="/edit/dev/imageListDeleteResizes">Delete Image Resizes</a>
        <a href="/edit/dev/cacheDeleteApp">Delete App Caches</a>
        <a href="/edit/dev/cacheDeleteEditor">Delete Editor Caches</a>
        <a href="/edit/dev/cacheDeleteAll">Delete ALL Caches</a>
    </div>

</div>
