<?php
// Copyright 2017-2022 Ino Detelić & Zaloa G. Ramos (setastart.com)
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\G;
use Galaxia\Text;
use GalaxiaEditor\E;


// @formatter:off
?>
<div id="dev" class="paper pad">

    <div class="paper-header pad">
        <h1><?=Text::t(E::$pgTitle);?></h1>
    </div>

    <div class="dev-actions pad">
<?php   if (G::$app->cookieDebugKey && G::$app->cookieDebugVal)  { ?>
        <div><button class="btn btn-pad btn-blue active ev-cookie-set" data-key="<?=Text::h(G::$app->cookieDebugKey)?>" data-val="<?=Text::h(G::$app->cookieDebugVal)?>"><?=Text::t("Set Cookie: Debug")?></button></div>
        <div><button class="btn btn-pad btn-blue active ev-cookie-del" data-key="<?=Text::h(G::$app->cookieDebugKey)?>"><?=Text::t("Delete Cookie: Debug")?></button></div>
<?php   } ?>
        <a href="/edit/dev/info"><?=Text::t('PHP Information')?></a>
        <a href="/edit/dev/sitemap"><?=Text::t('Regenerate Sitemap')?></a>
        <a href="/edit/dev/urls">URLs</a>
        <a href="/edit/dev/opcache"><?=Text::t('OPcache Status')?></a>
        <a href="/edit/dev/imageListDeleteResizes"><?=Text::t('Delete Image Resizes')?></a>
        <a href="/edit/dev/cacheDeleteApp"><?=Text::t('Delete App Caches')?></a>
        <a href="/edit/dev/cacheDeleteEditor"><?=Text::t('Delete Editor Caches')?></a>
        <a href="/edit/dev/cacheDeleteAll"><?=Text::t('Delete ALL Caches')?></a>
    </div>

</div>
