<?php
/*
 Copyright 2017-2020 Ino Detelić & Zaloa G. Ramos

  - Licensed under the EUPL, Version 1.2 only (the "Licence");
  - You may not use this work except in compliance with the Licence.

  - You may obtain a copy of the Licence at: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

  - Unless required by applicable law or agreed to in writing, software distributed
    under the Licence is distributed on an "AS IS" basis,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  - See the Licence for the specific language governing permissions and limitations under the Licence.
 */

ob_start();
phpinfo();
preg_match('~.*?<body>(.*)</body>~s', ob_get_clean(), $matches);

?>

<div id="dev" class="paper pad">

    <div class="paper-header pad">
        <h1>PHP Information</h1>
    </div>

    <div class="pad phpinfo">
        <?=$matches[1] ?? ''?>
    </div>

</div>
