<?php
// Copyright 2017-2023 Ino Detelić & Zaloa G. Ramos (setastart.com)
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\Text;

ob_start();
phpinfo();
preg_match('~.*?<body>(.*)</body>~s', ob_get_clean(), $matches);

// @formatter:off
?>

<div id="dev" class="paper pad">

    <div class="paper-header pad">
        <h1><?=Text::t('PHP Information')?></h1>
    </div>

    <div class="pad phpinfo">
        <?=$matches[1] ?? ''?>
    </div>

</div>
