<?php
// Copyright 2017-2024 Ino Detelić & Zaloa G. Ramos (setastart.com)
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\AppRoute;
use Galaxia\G;

$urls = AppRoute::urls(true);

// @formatter:off
?>

<div id="dev" class="paper pad">

    <div class="paper-header pad">
        <h1>All Urls (<?=count($urls)?>)</h1>
    </div>

    <div class="pad">
<?php   foreach ($urls as $url) { ?>
<?=G::$req->schemeHost(), $url, PHP_EOL?><br>
<?php   } ?>
    </div>

</div>
