<div class="history">
    <div class="item-title">
        <h1><?=h($pgTitle)?></h1>
    </div>
<?php if (isset($rootSlugs[$tabName])) { ?>
    <div class="paper-header">
        <a href="/edit/<?=h($rootSlugs[$tabName])?>/<?=h($tabId)?>"><?=t('Edit Item')?></a>
    </div>
<?php } ?>
<?php   foreach ($items as $itemId => $item) { ?>
    <div id="<?=h($itemId)?>" class="history-item paper pad action-<?=h($item['action'])?>">
<?php       foreach ($item['changes'] as $change) { ?>
        <div class="input-label pad"><span class="input-label-lang"><?=t($change['lang'])?></span> <?=t($change['name'])?></div>
        <div class="content pad"><?=strip_tags($change['content'], ALLOWED_TAGS)?></div>
<?php       } ?>
        <div class="paper-footer">
            <p class="pad"><?=t('action-' . $item['action'])?>: <?=gFormatDate($item['created'], 'd MMM y - HH:mm')?></p>
            <p class="grey pad"><?=t('Id')?>: <?=h($itemId)?></p>
        </div>
    </div>
<?php } ?>

</div>
