<?php
// Copyright 2017-2023 Ino Detelić & Zaloa G. Ramos (setastart.com)
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\G;
use Galaxia\Text;
use GalaxiaEditor\E;
use GalaxiaEditor\input\InputRender;

// @formatter:off
?>
<?php   InputRender::form('', 'image-resize', 'formPrevent image image-resize paper pad'); ?>

    <div class="paper-header pad">
        <h1><?=Text::st(E::$pgTitle)?></h1>
        <div class="paper-header-links">
            <a href="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$imgSlug)?>" class="btn-a"><?=Text::t('Go back')?></a>
        </div>
    </div>

    <div class="item-row">
<?php   $firstTime = true; ?>
<?php   $prefixPrev = null; ?>
<?php   foreach (E::$imgInputs as $input) { ?>
<?php       if (!$firstTime && ($prefixPrev == null || !isset($input['prefix']) || $input['prefix'] !== $prefixPrev)) { ?>
    </div>

    <div class="item-row">
<?php       } ?>
<?php       echo InputRender::renderInput($input); ?>
<?php       $firstTime = false; ?>
<?php       $prefixPrev = $input['prefix'] ?? ''; ?>
<?php   } ?>
    </div>

    <div class="image-preview pad">
        <figure>
            <?=G::image(E::$img), PHP_EOL?>
        </figure>
    </div>

    <div class="paper-footer pad">
<?php   include G::$editor->dirView . 'image/fragment/paper-footer-info.phtml'; ?>
        <div class="paper-footer-actions">
            <button class="btn btn-green active"><?=Text::t('Resize')?></button>
        </div>
    </div>

<?php   InputRender::renderFormEnd(); ?>
