<div id="dev" class="paper pad">

    <div class="paper-header pad">
        <h1><?=t($pgTitle);?></h1>
    </div>

    <div class="dev-actions pad">
<?php   if ($app->cookieDebugKey && $app->cookieDebugVal)  { ?>
        <div><button class="btn btn-pad btn-blue active" onclick="document.cookie = '<?=h($app->cookieDebugKey)?>=<?=h($app->cookieDebugVal)?>; expires=Fri, 31 Dec 9999 23:59:59 GMT; path=/'"><?=t("Set debug cookie")?></button></div>
        <div><button class="btn btn-pad btn-blue active" onclick="document.cookie = '<?=h($app->cookieDebugKey)?>=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/'"><?=t("remove debug cookie")?></button></div>
<?php   } ?>
        <a href="/edit/dev/sitemap">Regenerate Sitemap</a>
        <a href="/edit/dev/imageListDeleteResizes">Delete Image Resizes</a>
        <a href="/edit/dev/cacheDeleteApp">Delete App Caches</a>
        <a href="/edit/dev/cacheDeleteEditor">Delete Editor Caches</a>
        <a href="/edit/dev/cacheDeleteAll">Delete ALL Caches</a>
    </div>

</div>


