<?php
// Copyright 2017-2022 Ino Detelić & Zaloa G. Ramos (setastart.com)
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\G;
use Galaxia\Text;
use GalaxiaEditor\E;


// @formatter:off
?>
<div class="item-info">
    <div><?=Text::t('Original')?>: <a target="_blank" href="/media/image/<?=E::$imgSlug?>/<?=Text::h(E::$imgSlug . E::$img['ext'])?>"><?=Text::h(E::$img['wOriginal'] . 'x' . E::$img['hOriginal'])?></a><?=Text::h(E::$img['ext'])?>  (<?=Text::bytesIntToAbbr(filesize(G::dirImage() . E::$imgSlug . '/' . E::$imgSlug . E::$img['ext']))?>)</div>
<?php   foreach (E::$img['resizes'] as $fileName => $resize) { ?>
    <div>
        <?=Text::t('Dimensions')?>:
        <a target="_blank" href="/media/image/<?=E::$imgSlug?>/<?=Text::h($fileName)?>"><?=Text::h($resize)?></a>
        (<?=Text::bytesIntToAbbr(filesize(G::dirImage() . E::$imgSlug . '/' . $fileName))?>) <?=Text::h($fileName)?>
    </div>
<?php   } ?>

    <a class="<?=Text::h('active', E::$action == 'replace')?> btn-a" href="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$imgSlug)?>/replace"><?=Text::t('Replace Image')?></a>
    <a class="<?=Text::h('active', E::$action == 'resize')?> btn-a" href="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$imgSlug)?>/resize"><?=Text::t('Resize Image')?></a>
<?php   if (isset($item['gcDelete'])) { ?>
    <a class="<?=Text::h('active', E::$action == 'deleteResizes')?> btn-a" href="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$imgSlug)?>/deleteResizes"><?=Text::t('Delete Resizes')?></a>
    <a class="<?=Text::h('active', E::$action == 'deleteWebp')?> btn-a" href="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$imgSlug)?>/deleteWebp"><?=Text::t('Delete Webp')?></a>
    <a class="red<?=Text::h(' active', E::$action == 'delete')?> btn-a" href="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$imgSlug)?>/delete"><?=sprintf(Text::t('Delete %s'), Text::t(E::$section['gcTitleSingle']))?></a>
<?php   } ?>
</div>
