<?php

use Galaxia\Text;


?>
<div class="item-info">
    <div><?=Text::t('Original')?>: <a target="_blank" href="/media/image/<?=$imgSlug?>/<?=Text::h($imgSlug . $img['ext'])?>"><?=Text::h($img['wOriginal'] . 'x' . $img['hOriginal'])?></a><?=Text::h($img['ext'])?>  (<?=Text::bytesIntToAbbr(filesize($app->dirImage . $imgSlug . '/' . $imgSlug . $img['ext']))?>)</div>
<?php   foreach ($img['resizes'] as $fileName => $resize) { ?>
    <div>
        <?=Text::t('Dimensions')?>:
        <a target="_blank" href="/media/image/<?=$imgSlug?>/<?=Text::h($fileName)?>"><?=Text::h($resize)?></a>
        (<?=Text::bytesIntToAbbr(filesize($app->dirImage . $imgSlug . '/' . $fileName))?>) <?=Text::h($fileName)?>
    </div>
<?php   } ?>

    <a class="<?=Text::h('active', $action == 'replace')?> btn-a" href="/edit/<?=Text::h($pgSlug)?>/<?=Text::h($imgSlug)?>/replace"><?=Text::t('Replace Image')?></a>
    <a class="<?=Text::h('active', $action == 'resize')?> btn-a" href="/edit/<?=Text::h($pgSlug)?>/<?=Text::h($imgSlug)?>/resize"><?=Text::t('Resize Image')?></a>
<?php   if (isset($item['gcDelete'])) { ?>
    <a class="<?=Text::h('active', $action == 'deleteResizes')?> btn-a" href="/edit/<?=Text::h($pgSlug)?>/<?=Text::h($imgSlug)?>/deleteResizes"><?=Text::t('Delete Resizes')?></a>
    <a class="<?=Text::h('active', $action == 'deleteWebp')?> btn-a" href="/edit/<?=Text::h($pgSlug)?>/<?=Text::h($imgSlug)?>/deleteWebp"><?=Text::t('Delete Webp')?></a>
    <a class="red<?=Text::h(' active', $action == 'delete')?> btn-a" href="/edit/<?=Text::h($pgSlug)?>/<?=Text::h($imgSlug)?>/delete"><?=sprintf(Text::t('Delete %s'), Text::t($geConf[$pgSlug]['gcTitleSingle']))?></a>
<?php   } ?>
</div>
