<?php use GalaxiaEditor\input\InputRender;


InputRender::form('', 'image-list', 'paper pad');?>

    <div class="paper-header pad">
        <h1><span class="rowsFiltered"><?=h($rowsFiltered)?></span> &#8725; <span class="rowsTotal"><?=h($rowsTotal)?></span> <?=t($pgTitle);?></h1>

<?php   if (!empty($geConf[$pgSlug]['gcImageList']['gcLinks'])) { ?>
        <div class="list-actions">
<?php   foreach ($geConf[$pgSlug]['gcImageList']['gcLinks'] as $href => $link) { ?>
            <a href="/edit/<?=h($pgSlug)?>/<?=h($href)?>" class="btn btn-pad <?=h($link['cssClass'])?>"><?=sprintf(t('+ Add new %s'), t('Image'))?></a>
<?php   } ?>
        </div>
<?php   } ?>
<?php   if ($me->hasPerm('dev')) { ?>
        <div class="paper-header-links">
            <a href="/edit/dev/imageListDeleteResizes" class="hide-perm-dev btn-a"><?=t('Delete Resizes')?></a>
            <a href="/edit/dev/imageListReorder" class="hide-perm-dev btn-a"><?=t('Reorder Images')?></a>
        </div>
<?php   } ?>
    </div>




    <div class="filters filters-list">
<?php   if (!empty($filterTexts)) { ?>
<?php       foreach ($filterTexts as $filterId => $filter) { ?>
        <div class="input-wrap pad">
            <div class="input-label"><?=t($filter['label'])?></div>
<?php           if (empty($filter['filterEmpty'])) { ?>
            <input name="filterTexts[<?=$filterId?>]" class="input-text input-filter-text input-search br" type="search" value="<?=h($_POST['filterTexts'][$filterId] ?? '')?>">
<?php           } else { ?>
            <input name="filterTexts[<?=$filterId?>]" class="input-text input-filter-text input-search rl" type="search" value="<?=h($_POST['filterTexts'][$filterId] ?? '')?>">
            <label for="<?=h($filterId)?>-empty" class="btn btn-pill btn-checkbox rr">
                <?=t('Empty')?>
                <input class="filterChangeEmpty" type="checkbox" name="filterTexts[<?=$filterId?>]" value="{{empty}}" id="<?=h($filterId)?>-empty" title="<?=t('Empty')?>">
            </label>
<?php           } ?>
<?php           if ($filterId == 'type') { ?>
            <p class="small"><?=implode(', ', array_map('t', array_filter($geConf[$pgSlug]['gcImageTypes'])))?></p>
<?php           } ?>
        </div>
<?php       } ?>
<?php   } ?>

<?php   if (!empty($filterInts)) { ?>
<?php       foreach ($filterInts as $filterId => $filter) { ?>
        <div class="input-wrap input-filter-int pad">
            <div class="input-label"><?=t($filter['label'])?></div>
<?php       foreach ($filter['options'] as $key => $options) { ?>
            <label for="<?=h($filterId)?>-<?=h($key)?>" class="btn btn-pill btn-checkbox <?=h($options['cssClass'])?><?=($options['checked']) ? ' active' : ''?>">
                <?=t($options['label'])?>
                <input class="filterChange" name="filterInts[<?=$filterId?>][<?=h($key)?>]" type="checkbox" value="1" id="<?=h($filterId)?>-<?=h($key)?>" title="<?=t($options['label'])?>" <?=($options['checked']) ? ' checked' : ''?>>
            </label>
<?php       } ?>
        </div>
<?php       } ?>
<?php   } ?>
    </div>


<?php   renderPaginationHeader($pagination) ?>


    <div class="load">
<?php   include $editor->dirView . 'imageList/results.phtml'; ?>
    </div>


<?php   renderPaginationFooter($pagination) ?>


<?php   InputRender::renderFormEnd(); ?>
