<?php

use Galaxia\Pagination;


if (!isset($filterTexts)) {
    $filterTexts = [
        'slug' => [
            'label'       => 'Filter Slugs',
            'filterEmpty' => false,
        ],
        'alt' => [
            'label'       => 'Filter Alt',
            'filterEmpty' => true,
        ],
        'inuse' => [
            'label'       => 'Filter In Use',
            'filterEmpty' => true,
        ],
        'type' => [
            'label'       => 'Filter Types',
            'filterEmpty' => true,
        ],
    ];
} ?>
<?php   renderForm('/edit/' . $editor->imageSlug, 'image-select', 'hide');?>

    <div class="image-select-header pad">
        <h1><?=t('Select Image')?> <span class="rowsFiltered">0</span> &#8725; <span class="rowsTotal">0</span></h1>
        <div class="btn-group">
            <button type="button" class="btn-new btn-new-x-text rc image-select-header-close"><?=t("Close")?></button>
        </div>
        <div class="btn-group btn-group-gallery">
            <button type="button" class="btn-new btn-new-text rc image-select-header-select-all"><?=t("Select All")?></button>
        </div>
        <div class="btn-group btn-group-gallery">
            <button type="button" class="btn-new btn-new-text rc image-select-header-select-none"><?=t("Deselect All")?></button>
        </div>
        <div class="btn-group btn-group-gallery">
            <button type="button" class="btn-new btn-new-plus-text rc image-select-header-select"><?=t("Select")?></button>
        </div>
    </div>


    <div class="filters filters-list">
        <input type="hidden" name="imageListType" value="image-select">
<?php   if (!empty($filterTexts)) { ?>
<?php       foreach ($filterTexts as $filterId => $filter) { ?>
        <div class="input-wrap pad">
            <div class="input-label"><?=t($filter['label'])?></div>
<?php           if (empty($filter['filterEmpty'])) { ?>
            <input name="filterTexts[<?=$filterId?>]" class="input-text input-filter-text input-search br" type="search" value="<?=h($_POST['filterTexts'][$filterId] ?? '')?>">
<?php           } else { ?>
            <input name="filterTexts[<?=$filterId?>]" class="input-text input-filter-text input-search rl" type="search" value="<?=h($_POST['filterTexts'][$filterId] ?? '')?>">
            <label for="<?=h($filterId)?>-empty" class="btn btn-pill btn-checkbox rr">
                <?=t('Empty')?>
                <input class="filterChangeEmpty" type="checkbox" name="filterTexts[<?=$filterId?>]" value="{{empty}}" id="<?=h($filterId)?>-empty" title="<?=t('Empty')?>">
            </label>
<?php           } ?>
<?php           if ($filterId == 'type') { ?>
            <p class="small"><?=implode(', ', array_map('t', array_filter($geConf['images']['gcImageTypes'] ?? [])))?></p>
<?php           } ?>
        </div>
<?php       } ?>
<?php   } ?>
    </div>


<?php   $pagination = new Pagination(1, 100); ?>
<?php   $pagination->setItemsTotal(200); ?>
<?php   renderPaginationHeader($pagination) ?>


    <div id="imageSelector" class="load">
    </div>


<?php   renderPaginationFooter($pagination) ?>

<?php   renderFormEnd(); ?>
