<?php
// Copyright 2017-2022 Ino Detelić & Zaloa G. Ramos
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12


use Galaxia\Text;
use GalaxiaEditor\E;


// @formatter:off
?>
<div class="paper pad">

    <div class="paper-header pad">
        <h1>Basic Stats</h1>
    </div>

    <div class="stats-goaccess pad" data-room="/edit/chat">

        <div class="pad">
            <div class="row-head">
                <div class="col flex1">Tipo</div>
            </div>
        </div>

        <div class="list pad">
            <a class="row status-3" target="_blank" href="/edit/<?=E::$pgSlug?>/<?=date('Y-m-d')?>">
                <div class="col flex1">
                    <div class="col-text"><?=Text::t('Today')?></div>
                </div>
                <div class="col flex1">
                    <div class="col-text"><?=date('Y-m-d')?></div>
                </div>
            </a>
<?php   foreach (E::$statsGoaccess as $date) { ?>
<?php       $dt = date_create($date); ?>
            <a class="row status-3" target="_blank" href="/edit/<?=E::$pgSlug?>/<?=$date?>">
                <div class="col flex1">
                    <div class="col-text"><?=Text::h($dt->format('l'))?></div>
                </div>
                <div class="col flex1">
                    <div class="col-text"><?=Text::h($date)?></div>
                </div>
            </a>
<?php   } ?>
        </div>

    </div>
</div>
