<?php
// Copyright 2017-2023 Ino Detelić & Zaloa G. Ramos (setastart.com)
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\G;
use Galaxia\Text;
use GalaxiaEditor\E;
use GalaxiaEditor\input\InputRender;
use GalaxiaEditor\frag\FragPagination;


$links = [];
foreach ($list['gcLinks'] ?? [] as $href => $link) {
    if (!$link) continue;
    $frags = explode('/', $href);
    if (!$frags) continue;

    $label = Text::t($link['label'] ?? '');
    $href  = Text::h(E::$pgSlug) . '/' . $href;
    $css   = Text::h($link['cssClass'] ?? '');

    $padCss = 'pad padv';
    foreach ($link['gcPerms'] ?? [] as $perm) {
        $padCss .= ' hide-perm-' . Text::h($perm);
    }



    switch ($frags[0]) {
        case 'new':
            $label = sprintf(Text::t('+ Add new %s'), Text::t(E::$section['gcTitleSingle']));
            break;

        case 'order':
            $label = sprintf(Text::t('Order %s'), Text::t(E::$section['gcTitlePlural']));
            break;

        default:
            break;
    }
    $links[] = [
        'label'  => $label,
        'href'   => $href,
        'css'    => $css,
        'padCss' => $padCss,
    ];
}

// @formatter:off
?>
<?php   InputRender::form('', 'item-list', 'paper pad'); ?>

    <div class="paper-header">
        <h1 class="pad"><span class="rowsFiltered"><?=E::$pagination->itemsFiltered?></span> &#8725; <span class="rowsTotal"><?=E::$pagination->itemsTotal?></span> <?=Text::t(E::$pgTitle);?></h1>

        <div class="list-links">
<?php   foreach ($links as $link) { ?>
            <div class="<?=$link['padCss']?>"><a href="/edit/<?=Text::h($link['href'])?>" class="btn btn-pad <?=Text::h($link['css'])?>"><?=Text::t($link['label'])?></a></div>
<?php   } ?>
        </div>
    </div>

    <div class="filters filters-list">
<?php   if (!empty($filterTexts)) { ?>
<?php       foreach ($filterTexts as $filterId => $filter) {
                if (!$filter) continue;
                $filterCss = '';
                foreach ($filter['gcPerms'] ?? [] as $perm) {
                    $filterCss .= ' hide-perm-' . Text::h($perm);
                }
        ?>
        <div class="input-wrap pad<?=$filterCss?>">
            <div class="input-label"><div><?=Text::t($filter['label'])?></div></div>
            <div class="input-inputs">
<?php           if (empty($filter['filterEmpty'])) { ?>
                <input name="filterTexts[<?=$filterId?>]" class="input-text input-filter-text input-search br" type="search" value="<?=Text::h($_POST['filterTexts'][$filterId] ?? '')?>">
<?php           } else { ?>
                <input name="filterTexts[<?=$filterId?>]" class="input-text input-filter-text input-search rl" type="search" value="<?=Text::h($_POST['filterTexts'][$filterId] ?? '')?>">
                <label for="<?=Text::h($filterId)?>-empty" class="btn btn-pill btn-checkbox rr">
                    <?=Text::t('Empty')?>
                    <input class="filterChangeEmpty" type="checkbox" name="filterTexts[<?=$filterId?>]" value="{{empty}}" id="<?=Text::h($filterId)?>-empty" title="<?=Text::t('Empty')?>">
                </label>
<?php           } ?>
            </div>
        </div>
<?php       } ?>
<?php   } ?>

<?php   if (!empty($filterInts)) { ?>
<?php       foreach ($filterInts as $filterId => $filter) {
                if (!$filter) continue;
                $filterCss = '';
                foreach ($filter['gcPerms'] ?? [] as $perm) {
                    $filterCss .= ' hide-perm-' . Text::h($perm);
                }
?>
        <div class="input-wrap input-filter-int pad<?=$filterCss?>">
            <div class="input-label"><div><?=Text::t($filter['label'] ?? '')?></div></div>
            <div class="input-inputs">
<?php       foreach ($filter['options'] ?? [] as $key => $options) { ?>
                <label for="<?=Text::h($filterId)?>-<?=Text::h($key)?>" class="btn btn-pill btn-checkbox <?=Text::h($options['cssClass'] ?? '')?><?=($options['checked']) ? ' active' : ''?>">
                    <?=Text::t($options['label'])?>
                    <input class="filterChange" name="filterInts[<?=$filterId?>][<?=Text::h($key)?>]" type="checkbox" value="1" id="<?=Text::h($filterId)?>-<?=Text::h($key)?>" title="<?=Text::t($options['label'])?>" <?=($options['checked']) ? ' checked' : ''?>>
                </label>
<?php       } ?>
            </div>
        </div>
<?php       } ?>
<?php   } ?>
    </div>


<?php FragPagination::renderHeader(E::$pagination) ?>


    <div class="load">
<?php   include G::$editor->dirView . 'list/results.phtml'; ?>
    </div>


<?php FragPagination::renderFooter(E::$pagination) ?>


<?php   InputRender::renderFormEnd(); ?>
