<?php
// Copyright 2017-2023 Ino Detelić & Zaloa G. Ramos (setastart.com)
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\G;
use Galaxia\Text;
use GalaxiaEditor\E;
use GalaxiaEditor\input\InputRender;


// @formatter:off
?>
<?php   InputRender::form('', 'item-order', 'formPrevent paper pad'); ?>

    <div class="paper-header pad">
        <h1><?=Text::t(E::$pgTitle)?></h1>
        <div class="list-links">
        </div>
        <div class="paper-header-actions">
            <button type="submit" class="btn btn-green active"><?=Text::t('Save')?></button>
            <button class="btn btn-blue active" name="submitAndGoBack"><?=Text::t('Save and go back')?></button>
        </div>

    </div>


    <div class="load">
<?php   include G::$editor->dirView . 'list/results.phtml'; ?>
    </div>

    <div class="paper-footer pad">
        <div class="paper-footer-actions">
            <button type="submit" class="btn btn-green active"><?=Text::t('Save')?></button>
            <button class="btn btn-blue active" name="submitAndGoBack"><?=sprintf(Text::t('Save and go back to %s'), Text::t(E::$section['gcTitlePlural']))?></button>
        </div>
    </div>

<?php   InputRender::renderFormEnd(); ?>
