<?php
// Copyright 2017-2022 Ino Detelić & Zaloa G. Ramos (setastart.com)
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\Text;
use GalaxiaEditor\E;


// @formatter:off
?>
<div class="paper pad">

    <div class="paper-header pad">
        <h1><?=Text::t(E::$pgTitle);?></h1>
    </div>

    <div class="gchat-room pad" data-room="/edit/chat">
        <div class="title"><?=Text::t(E::$pgTitle);?></div>
        <div class="users"></div>
        <div class="messages-wrapper">
            <div class="s0w s1w messages">
            </div>
        </div>
        publish status: <span class="status-publish"></span>
        <div class="send input-wrap input-wrap-textarea">
            <div class="input-label">
                <div><?=Text::t('Send message')?></div>
            </div>
            <div class="input-inputs">
                <textarea class="gchat-room-text input-text input-textarea rl" name="msg" rows="1" wrap="soft" data-room="/edit/chat"></textarea>
                <button class="gchat-room-btn btn btn-green active rr" data-room="/edit/chat"><?=Text::t('Send')?></button>
            </div>
        </div>
    </div>

    listen status: <span id="status-listen"></span>

</div>
