<?php use GalaxiaEditor\input\InputRender;


InputRender::form('', 'item-edit', 'item paper pad'); ?>

    <div class="paper-header pad">
        <h1><?=h($pgTitle)?></h1>

<?php   if ($firstStatus) { ?>
<?php       echo InputRender::status($item['inputs'][$firstStatus]); ?>
<?php   } ?>

        <div class="paper-header-actions">
            <button type="submit" class="btn btn-green active"><?=t('Save')?></button>
            <button class="btn btn-blue active" name="submitAndGoBack"><?=t('Save and go back')?></button>
        </div>

        <div class="paper-header-links">
            <a href="/edit/<?=h($pgSlug)?>/<?=h($itemId)?>" class="btn-a"><?=t('Reload')?></a>
<?php   if ($item['gcVisit']) { ?>
            <?=t('Open in new tab')?>:
<?php   } ?>

<?php   if (is_int($item['gcVisit']) || (is_bool($item['gcVisit']) && $item['gcVisit'])) { ?>
<?php       foreach ($app->langs as $lang) { ?>
<?php           if (isset($item['inputs']['slug_' . $lang])) { ?>
            <a target="_blank" rel="noreferrer" href="<?=$app->addLangPrefix($pageById[$item['gcVisit']]['slug'][$lang] . '/' . $item['inputs']['slug_' . $lang]['value'], $lang)?>" class="btn-a"><?=h($lang)?></a>
<?php           } else if (isset($item['inputs'][$item['gcTable'] . 'Slug_' . $lang])) { ?>
            <a target="_blank" rel="noreferrer" href="<?=$app->addLangPrefix($pageById[$item['gcVisit']]['slug'][$lang] . '/' . $item['inputs'][$item['gcTable'] . 'Slug_' . $lang]['value'], $lang)?>" class="btn-a"><?=h($lang)?></a>
<?php           } ?>
<?php       } ?>
<?php   } else if (is_array($item['gcVisit'])) { ?>
<?php       foreach ($item['gcVisit'] as $link) { ?>
<?php           if (!isset($link['id'])) continue ?>
<?php           if (!isset($link['prefix'])) continue ?>
<?php           $id = $item['inputs'][$link['id']]['value'] ?? ''; ?>
<?php           $prefix = $link['prefix'] ?? ''; ?>
<?php           $name = $prefix . $item['inputs'][$link['id']]['value']; ?>
            <a target="_blank" rel="noreferrer" href="<?=h($name)?>" class="btn-a"><?=h($name)?></a>
<?php       } ?>
<?php   } ?>
        </div>
    </div>


<?php   if ($item['inputs'] ?? []) { ?>
    <div class="item-row">
<?php       $firstTime = true; ?>
<?php       $prefixPrev = null; ?>
<?php       foreach ($item['inputs'] as $inputKey => $input) { ?>
<?php           if ($inputKey == $firstStatus) continue; ?>
<?php           if (!$firstTime && ($prefixPrev == null || !isset($input['prefix']) || $input['prefix'] !== $prefixPrev)) { ?>
    </div>

    <div class="item-row">
<?php           } ?>
<?php           echo InputRender::renderInput($app, $input); ?>
<?php           $firstTime = false; ?>
<?php           $prefixPrev = $input['prefix'] ?? null; ?>
<?php       } ?>
    </div>
<?php   } ?>


<?php

foreach ($modules as $moduleKey => $module) {
    if (!$module['inputs'] ?? []) continue;
    switch ($module['gcModuleType']) {
        case 'fields':
            if (empty($module['inputs'])) {
                $foundMulti = false;
                if (!empty($module['gcModuleMultiple'])) {
                    $foundMulti = true;
                    break;
                }
                if (!$foundMulti) continue 2;
            }
            include $editor->dirView . 'item/modules/fields.phtml';
            break;
        default:
            geErrorPage(500, 'invalid phtml module');
            break;
    }
}

?>


    <div class="paper-footer pad">
        <div class="item-info">
<?php   if ($item['gcInfo']) { ?>
<?php       foreach ($item['gcInfo'] as $info) { ?>
            <p><?=t($info['label'])?>: <?=h($info['value'])?></p>
<?php       } ?>
<?php   } ?>
            <a target="_blank" href="/edit/history/<?=h($item['gcTable'])?>/<?=h($itemId)?>" class="btn-a"><?=t('Open History in a new tab')?></a>
<?php   if ($me->hasPerm('dev')) { ?>
            <a href="/edit/<?=h($pgSlug)?>/<?=h($itemId)?>/history" class="hide-perm-dev btn-a"><?=sprintf(t('Save %s in History'), t($geConf[$pgSlug]['gcTitleSingle']))?></a>
<?php   } ?>
<?php   if ($item['gcDelete']) { ?>
            <a href="/edit/<?=h($pgSlug)?>/<?=h($itemId)?>/delete" class="red btn-a"><?=sprintf(t('Delete %s'), t($geConf[$pgSlug]['gcTitleSingle']))?></a>
<?php   } ?>
        </div>
        <div class="paper-footer-actions">
            <button type="submit" class="btn btn-green active"><?=t('Save')?></button>
            <button class="btn btn-blue active" name="submitAndGoBack"><?=sprintf(t('Save and go back to %s'), t($geConf[$pgSlug]['gcTitlePlural']))?></button>
        </div>
    </div>

<?php   InputRender::renderFormEnd(); ?>
