<?php use Galaxia\AppImage;
use Galaxia\Text;
use GalaxiaEditor\input\InputRender;


InputRender::form('', 'image-edit', 'image image-new paper pad'); ?>

    <div class="paper-header pad">
        <h1><?=Text::st($pgTitle)?></h1>

        <div class="paper-header-actions">
            <button type="submit" class="btn btn-green active"><?=Text::t('Save')?></button>
            <button class="btn btn-blue active" name="submitAndGoBack"><?=Text::t('Save and go back')?></button>
        </div>

        <div class="paper-header-links">
            <a href="/edit/<?=Text::h($pgSlug)?>/<?=Text::h($imgSlug)?>" class="btn-a"><?=Text::t('Reload')?></a>
        </div>
    </div>

    <div class="item-row">
<?php   $firstTime = true; ?>
<?php   $prefixPrev = null; ?>
<?php   foreach ($inputs as $input) { ?>
<?php       if (!$firstTime && ($prefixPrev == null || !isset($input['prefix']) || $input['prefix'] !== $prefixPrev)) { ?>
    </div>

    <div class="item-row">
<?php       } ?>
<?php       echo InputRender::renderInput($app, $input); ?>
<?php       $firstTime = false; ?>
<?php       $prefixPrev = $input['prefix'] ?? ''; ?>
<?php   } ?>
    </div>

    <div class="image-preview pad">
        <figure>
            <?=AppImage::render($img), PHP_EOL?>
        </figure>
    </div>

    <div class="paper-footer pad">
<?php   include $editor->dirView . 'image/fragment/paper-footer-info.phtml'; ?>
        <div class="paper-footer-actions">
            <button class="btn btn-green active"><?=Text::t('Save')?></button>
            <button class="btn btn-blue active" name="submitAndGoBack"><?=sprintf(Text::t('Save and go back to %s'), Text::t($geConf[$pgSlug]['gcTitlePlural']))?></button>
        </div>
    </div>

<?php   InputRender::renderFormEnd(); ?>
