<?php

use Galaxia\G;
use Galaxia\Text;
use GalaxiaEditor\E;
use GalaxiaEditor\input\InputRender;


InputRender::form('', 'image-delete', 'image image-delete paper pad'); ?>

    <div class="paper-header pad">
        <h1><?=Text::st(E::$pgTitle)?></h1>
        <div class="paper-header-links">
            <a href="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$imgSlug)?>" class="btn-a"><?=Text::t('Go back')?></a>
        </div>
    </div>

    <div class="image-preview pad">
        <figure>
            <?=G::image($img), PHP_EOL?>
        </figure>
    </div>

    <div class="paper-footer pad">
<?php   include $editor->dirView . 'image/fragment/paper-footer-info.phtml'; ?>
        <div class="paper-footer-actions">
            <a class="btn btn-blue btn-mb active" href="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$imgSlug)?>"><?=Text::t('Cancel')?></a>
            <button class="btn btn-red btn-mb active"><?=sprintf(Text::t('Delete %s'), Text::t(E::$section['gcTitleSingle']))?></button>
        </div>
    </div>

<?php   InputRender::renderFormEnd(); ?>
