<?php
// Copyright 2017-2024 Ino Detelić & Zaloa G. Ramos (setastart.com)
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\G;
use Galaxia\Text;
use GalaxiaEditor\E;
use GalaxiaEditor\input\InputRender;

// @formatter:off
?>
<?php   InputRender::form('', 'image-delete', 'image image-delete paper pad'); ?>

    <div class="paper-header pad">
        <h1><?=Text::st(E::$pgTitle)?></h1>
        <div class="paper-header-links">
            <a href="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$imgSlug)?>" class="btn-a"><?=Text::t('Go back')?></a>
        </div>
    </div>

    <div class="image-preview pad">
        <figure>
            <?=G::image(E::$img), PHP_EOL?>
        </figure>
    </div>

    <div class="paper-footer pad">
<?php   include G::$editor->dirView . 'image/fragment/paper-footer-info.phtml'; ?>
        <div class="paper-footer-actions">
            <a class="btn btn-blue btn-mb active" href="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$imgSlug)?>"><?=Text::t('Cancel')?></a>
            <button class="btn btn-red btn-mb active"><?=sprintf(Text::t('Delete %s'), Text::t(E::$section['gcTitleSingle']))?></button>
        </div>
    </div>

<?php   InputRender::renderFormEnd(); ?>
