<?php use Galaxia\G;
use Galaxia\Text;
use GalaxiaEditor\input\InputRender;


InputRender::form('', 'item-delete', 'item item-delete paper pad'); ?>

    <div class="paper-header pad">
        <h1><?=Text::st($pgTitle)?></h1>
    </div>

    <div class="item-delete-review">

        <div class="item-row">
<?php   $firstTime = true; ?>
<?php   $prefixPrev = null; ?>
<?php   foreach ($item['inputs'] as $input) { ?>
<?php       if (!$firstTime && ($prefixPrev == null || !isset($input['prefix']) || $input['prefix'] !== $prefixPrev)) { ?>
        </div>
        <div class="item-row">
<?php       } ?>
<?php       echo InputRender::renderInputText($input); ?>
<?php       $firstTime = false; ?>
<?php       $prefixPrev = $input['prefix'] ?? null; ?>
<?php   } ?>
        </div>

        <div class="item-row">
<?php   foreach ($modules as $module) { ?>
<?php       foreach ($module['inputs'] as $fieldName => $field) { ?>
<?php           $prefixPrev = null; ?>
<?php           foreach ($field as $input) { ?>
<?php               if (!isset($input['value'])) continue; ?>
<?php               if ($fieldName !== $prefixPrev) { ?>
        </div>
        <div class="item-row">
<?php               } ?>
<?php               echo InputRender::renderInputText($input); ?>
<?php               $prefixPrev = $fieldName; ?>
<?php           } ?>
<?php       } ?>
<?php   } ?>
        </div>

    </div>

    <div class="paper-footer pad">
        <div class="item-info">
            <h2><?=sprintf(Text::t('Delete %s'), Text::t(G::$conf[$pgSlug]['gcTitleSingle']))?>?</h2>
            <p><?=Text::t('This action is permanent.')?></p>
        </div>
        <div class="paper-footer-actions">
            <a class="btn btn-blue active" href="/edit/<?=Text::h($pgSlug)?>/<?=Text::h($itemId)?>"><?=Text::t('Cancel')?></a>
            <button class="btn btn-red active"><?=sprintf(Text::t('Delete %s'), Text::t(G::$conf[$pgSlug]['gcTitleSingle']))?></button>
        </div>
    </div>

<?php   InputRender::renderFormEnd(); ?>
