<?php
// Copyright 2017-2022 Ino Detelić & Zaloa G. Ramos (setastart.com)
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\Text;
use GalaxiaEditor\E;
use GalaxiaEditor\input\InputRender;

// @formatter:off
?>
<?php   InputRender::form('', 'item-delete', 'item item-delete paper pad'); ?>

    <div class="paper-header pad">
        <h1><?=Text::st(E::$pgTitle)?></h1>
    </div>

    <div class="item-delete-review">

        <div class="item-row">
<?php   $firstTime = true; ?>
<?php   $prefixPrev = null; ?>
<?php   foreach (E::$item['inputs'] as $input) { ?>
<?php       if (!$firstTime && ($prefixPrev == null || !isset($input['prefix']) || $input['prefix'] !== $prefixPrev)) { ?>
        </div>
        <div class="item-row">
<?php       } ?>
<?php       echo InputRender::renderInputText($input); ?>
<?php       $firstTime = false; ?>
<?php       $prefixPrev = $input['prefix'] ?? null; ?>
<?php   } ?>
        </div>

        <div class="item-row">
<?php   foreach (E::$modules as $module) { ?>
<?php       foreach ($module['inputs'] as $fieldName => $field) { ?>
<?php           $prefixPrev = null; ?>
<?php           foreach ($field as $input) { ?>
<?php               if (!isset($input['value'])) continue; ?>
<?php               if ($fieldName !== $prefixPrev) { ?>
        </div>
        <div class="item-row">
<?php               } ?>
<?php               echo InputRender::renderInputText($input); ?>
<?php               $prefixPrev = $fieldName; ?>
<?php           } ?>
<?php       } ?>
<?php   } ?>
        </div>

    </div>

    <div class="paper-footer pad">
        <div class="item-info">
            <h2><?=sprintf(Text::t('Delete %s'), Text::t(E::$section['gcTitleSingle']))?>?</h2>
            <p><?=Text::t('This action is permanent.')?></p>
        </div>
        <div class="paper-footer-actions">
            <a class="btn btn-blue active" href="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$itemId)?>"><?=Text::t('Cancel')?></a>
            <button class="btn btn-red active"><?=sprintf(Text::t('Delete %s'), Text::t(E::$section['gcTitleSingle']))?></button>
        </div>
    </div>

<?php   InputRender::renderFormEnd(); ?>
