<?php
// Copyright 2017-2022 Ino Detelić & Zaloa G. Ramos
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// You may obtain a copy of the Licence at: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\Text;
use GalaxiaEditor\E;
use GalaxiaEditor\input\InputRender;


$userEmail = (isset($_SESSION['post']['userEmail'])) ? Text::h($_SESSION['post']['userEmail']) : ''

// @formatter:off
?>

<form action="/edit/login" method="post" autocomplete="on">

<?php   foreach (E::$loginInputs as $input) { ?>
<?php       echo InputRender::renderInput($input); ?>
<?php   } ?>


    <div class="input-wrap pad">
        <div class="input-label"></div>
        <button class="btn btn-green active" type="submit">Login</button>
    </div>

</form>
