<?php

use Galaxia\G;
use Galaxia\Flash;
use Galaxia\Text;


global $editor;
global $geConf;
global $pgSlug;
global $me;
?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <title>Error <?=Text::h($errorCode)?></title>

    <link rel="shortcut icon" href="/edit/favicon.ico?version=<?=Text::h($editor->version)?>">

    <link rel="stylesheet" href="/edit/css/reset.css?version=<?=Text::h($editor->version)?>">
    <link rel="stylesheet" href="/edit/css/text.css?version=<?=Text::h($editor->version)?>">
    <link rel="stylesheet" href="/edit/css/galaxiaEditor.css?version=<?=Text::h($editor->version)?>">
    <link rel="stylesheet" href="/edit/css/forms.css?version=<?=Text::h($editor->version)?>">
    <link rel="stylesheet" href="/edit/css/filters.css?version=<?=Text::h($editor->version)?>">
    <link rel="stylesheet" href="/edit/css/responsive.css?version=<?=Text::h($editor->version)?>">

    <script type="text/javascript" src="/edit/js/galaxiaEditor.js?version=<?=Text::h($editor->version)?>"></script>
</head>
<body class="page-error">

<div id="openboxes">
</div>

<?php   include 'menu.phtml'; ?>

<div id="page">
<?php   include 'messageBoxes.phtml'; ?>
    <div class="paper pad">
        <div class="paper-header pad">
            <h1>Error <?=Text::h($errorCode)?></h1>
        </div>
        <div class="pad">
            <?=nl2br($error)?>
        </div>
<?php   if (G::isDevDebug()) { ?>
        <div class="pad">
            <?php db(); ?>
        </div>
<?php   } ?>
    </div>
</div>

<div id="footer">
    <div class="links">
        <a href="/edit/logout"><?=Text::t('Logout')?></a>
<?php   if ($me->hasPerm('dev')) { ?>
        <a href="/edit/dev" class="hide-perm-dev">Developer</a>
<?php   } ?>
        <a href="/edit/dev/cacheDeleteEditor"><?=Text::t('Delete Editor Caches')?></a>
    </div>
    <p class="version"><img class="icon" src="/edit/favicon.ico"><?=Text::h($me->name)?>@GalaxiaEditor v<?=Text::h($editor->version);?></p>
    <p class="copy"><img class="icon" src="/edit/gfx/icon-setastart-white-32.png"/><a href="https://setastart.com/" target="_blank">setastart.com</a> &copy; 2017-<?=date("Y")?></p>
</div>

</body>
</html>
<?php   Flash::cleanMessages(); ?>
