<?php
// Copyright 2017-2022 Ino Detelić & Zaloa G. Ramos (setastart.com)
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\Flash;
use Galaxia\G;
use Galaxia\Text;
use GalaxiaEditor\E;
use GalaxiaEditor\frag\FragMenu;
use GalaxiaEditor\frag\FragMsgBoxes;


$permColors = [
    'dev'   => '#fe9',
    'admin' => '#dcf',
];

$menuRight = ((G::$me->options['menuPosition'] ?? '') == 'right');


// @formatter:off
?>
<!DOCTYPE html>
<html lang="<?=Text::h(G::lang())?>">
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex">

    <title><?=Text::h(E::$hdTitle)?></title>

    <link rel="shortcut icon" href="/edit/favicon.ico?version=<?=Text::h(G::$editor->version)?>">

    <script type="text/javascript">
// switches for hiding perms & langs
window.addEventListener("DOMContentLoaded", function(event) {
    var switches = document.querySelectorAll('#switches label');
    for (i = 0; i < switches.length; i++) {
        if (window.location.pathname.endsWith('/new')) break;
        if (switches[i].classList.contains('btn-red')) continue;

        if (switches[i].dataset.remember) {
            if (switches[i].classList.contains('active')) {
                if (sessionStorage.getItem(switches[i].children[0].value) === 'hide') {
                    switches[i].classList.remove('active');
                    switches[i].children[0].checked = false;
                }
            } else {
                if (sessionStorage.getItem(switches[i].children[0].value) === 'show') {
                    switches[i].classList.add('active');
                    switches[i].children[0].checked = true;
                }
            }
        }

        if (!switches[i].classList.contains('active')) {
            document.body.classList.add(switches[i].children[0].value);
        }
    }
});
    </script>

    <link rel="stylesheet" href="/edit/css/reset.css?version=<?=Text::h(G::$editor->version)?>">
    <link rel="stylesheet" href="/edit/css/text.css?version=<?=Text::h(G::$editor->version)?>">
    <link rel="stylesheet" href="/edit/css/galaxiaEditor.css?version=<?=Text::h(G::$editor->version)?>">
    <link rel="stylesheet" href="/edit/css/forms.css?version=<?=Text::h(G::$editor->version)?>">
    <link rel="stylesheet" href="/edit/css/filters.css?version=<?=Text::h(G::$editor->version)?>">
<?php   if (E::$chatInclude) { ?>
    <link rel="stylesheet" href="/edit/css/chat.css?version=<?=Text::h(G::$editor->version)?>">
<?php   } ?>
    <link rel="stylesheet" href="/edit/css/responsive.css?version=<?=Text::h(G::$editor->version)?>">
<?php   if (E::$includeTrix) { ?>
    <link rel="stylesheet" href="/edit/css/trix.css?version=<?=Text::h(G::$editor->version)?>">
<?php   } ?>
    <style>
<?php   foreach (G::langs() as $lang) { ?>
.hide-active-lang-<?=Text::h($lang)?> .hide-lang-<?=Text::h($lang)?> { display: none; }
<?php   } ?>
<?php   foreach (G::$me->perms as $perm) { ?>
.hide-active-perm-<?=Text::h($perm)?> .hide-perm-<?=Text::h($perm)?> { display: none; }
.hide-active-perm-<?=Text::h($perm)?> #menu .hide-perm-<?=Text::h($perm)?> { display: flex; opacity: 0.4; box-shadow: none; }
.hide-perm-<?=Text::h($perm)?> { background-color: <?=$permColors[$perm] ?? '#ddd'?>; }
.paper-header-status.hide-perm-<?=Text::h($perm)?> { padding: 5px 5px 3px; }
<?php   } ?>
    </style>

    <script type="text/javascript" src="/edit/js/galaxiaEditor.js?version=<?=Text::h(G::$editor->version)?>"></script>
    <script type="text/javascript">gjImage.editorImageSlug = '<?=Text::h(G::$editor->imageSlug)?>';</script>
<?php   if (E::$hookTranslate) { ?>
    <script type="text/javascript">
let gtranslate = '<?=E::$hookTranslate?>';
    </script>
<?php   } ?>
<?php   if (E::$chatInclude) { ?>
    <script type="text/javascript">
var gchat = {
    'enabled'       : false,
    'myId'          : '<?=G::$me->id?>',
    'clientId'      : '<?=uniqid(true)?>',
    'csrf'          : '<?=$_SESSION['csrf']?>',
    'listenXhr'     : false,
    'listenTimeout' : false,
    'listenStatus'  : false,
    'roomNodes'     : {},
    'rooms'         : {},
    'leaving'       : false,
    'lang'          : '<?=G::lang()?>',
};
    </script>
    <script type="text/javascript" src="/edit/js/galaxiaChat.js?version=<?=Text::h(G::$editor->version)?>"></script>
<?php   } ?>
<?php   if (E::$includeTrix) { ?>
    <script type="text/javascript" src="/edit/js/gtrix-1.3.1g.min.js?version=<?=Text::h(G::$editor->version)?>" async defer></script>
<?php   } ?>
</head>

<?php
$bodyClasses = '';
if ($menuRight) $bodyClasses .= ' menu-right';
if (G::isDevDebug()) $bodyClasses .= ' isDevDebug';
if (G::isDevEnv()) $bodyClasses .= ' isDevEnv';
?>
<body class="page-<?=Text::h(E::$pgSlug)?> hide-active-msgbox-info hide-active-msgbox-warning hide-active-msgbox-error hide-active-msgbox-devlog<?=Text::h($bodyClasses)?>">

<div id="openboxes">
<?php   foreach (['error', 'info', 'warning'] as $box) { ?>
<?php       if ($msgs = Flash::msgBoxes($box)) { ?>
    <div id="openbox-<?=Text::h($box)?>" class="openbox">
        <label for="switch-hide-msgbox-<?=Text::h($box)?>" class="btn btn-pill btn-small btn-checkbox">
            <?=Text::t(ucfirst($box))?>
            <input autocomplete="off" type="checkbox" value="hide-active-msgbox-<?=Text::h($box)?>" id="switch-hide-msgbox-<?=Text::h($box)?>" title="<?=Text::h($box)?>">
        </label>
        <span><?=$msgs[0] . ((count($msgs) > 1) ? ' +' . (count($msgs) - 1) : '')?></span>
    </div>
<?php       } ?>
<?php   } ?>
<?php   if (G::isDev()) { ?>
<?php       $box = 'devlog'; ?>
<?php       if ($msgs = Flash::msgBoxes($box)) { ?>
    <div id="openbox-<?=Text::h($box)?>" class="openbox hide-perm-dev">
        <label for="switch-hide-msgbox-<?=Text::h($box)?>" class="btn btn-pill btn-small btn-checkbox">
            <?=Text::t(ucfirst($box))?>
            <input autocomplete="off" type="checkbox" value="hide-active-msgbox-<?=Text::h($box)?>" id="switch-hide-msgbox-<?=Text::h($box)?>" title="<?=Text::h($box)?>">
        </label>
        <span><?=Text::desc($msgs[0], 30, ' ') . ((count($msgs) > 1) ? ' +' . (count($msgs) - 1) : '')?></span>
    </div>
<?php       } ?>
<?php   } ?>
</div>

<?php   if (!$menuRight) FragMenu::render(); ?>

<div id="page">
<?php   FragMsgBoxes::render(); ?>
<?php   G::timerStart('View: ' . G::$editor->view . '.phtml'); ?>
<?php   require G::$editor->dirView . G::$editor->view . '.phtml'; ?>
<?php   G::timerStop('View: ' . G::$editor->view . '.phtml'); ?>
</div>

<?php   if ($menuRight) FragMenu::render(); ?>

<div id="footer">
    <div class="links">
        <a href="/edit/logout"><?=Text::t('Logout')?></a>
<?php   if (G::isDev()) { ?>
        <a href="/edit/dev" class="hide-perm-dev"><?=Text::t('🛠 Dev')?></a>
<?php   } ?>
        <a href="/edit/dev/cacheDeleteEditor"><?=Text::t('Delete Editor Caches')?></a>
    </div>
    <p class="version"><img class="icon" alt="Icon" src="/edit/favicon.ico"><?=Text::h(G::$me->name)?>@GalaxiaEditor <?=Text::h(G::$editor->version);?></p>
    <p class="copy"><img class="icon" alt="Setastart Icon" src="/edit/gfx/icon/icon-setastart-white-32.png"/><a href="https://setastart.com/" target="_blank">setastart.com</a> &copy; 2017-<?=date("Y")?></p>
</div>


<?php   require G::$editor->dirView . 'imageList/select.phtml'; ?>


<?php   if (E::$chatInclude && E::$pgSlug != 'chat') { ?>
<div id="gchat">
<?php       if (E::$chatIncludeCurrent) { ?>
    <div class="gchat-room" data-room="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$itemId)?>">
        <div class="title"><?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$itemId)?></div>
        <div class="users"></div>
        <div class="messages-wrapper">
            <div class="s0w s1w messages">
            </div>
        </div>
        <span class="status-publish"></span>
        <div class="send">
            <textarea class="gchat-room-text input-text input-textarea" name="msg" rows="1" data-room="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$itemId)?>" wrap="soft"></textarea>
            <button class="gchat-room-btn btn btn-green" data-room="/edit/<?=Text::h(E::$pgSlug)?>/<?=Text::h(E::$itemId)?>"><?=Text::t('Send')?></button>
        </div>
    </div>
<?php       } ?>
    <div class="gchat-room" data-room="/edit/chat">
        <div class="title"><?=E::$conf['chat']['gcMenuTitle']?></div>
        <div class="users"></div>
        <div class="messages-wrapper">
            <div class="s0w s1w messages">
            </div>
        </div>
        <span class="status-publish"></span>
        <div class="send">
            <textarea class="gchat-room-text input-text input-textarea" name="msg" rows="1" data-room="/edit/chat" wrap="soft"></textarea>
            <button class="gchat-room-btn btn btn-green" data-room="/edit/chat"><?=Text::t('Send')?></button>
        </div>
    </div>
    <div id="status-listen">listen status</div>
</div>
<?php   } ?>

</body>
</html>
<?php   Flash::cleanMessages(); ?>
