<?php

use Galaxia\Flash;
use Galaxia\G;
use Galaxia\Text;
use GalaxiaEditor\E;


?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex">

    <title><?=Text::h(E::$hdTitle)?></title>

    <link rel="shortcut icon" href="/edit/favicon.ico?version=<?=Text::h(G::$editor->version)?>">

    <link rel="stylesheet" href="/edit/css/reset.css?version=<?=Text::h(G::$editor->version)?>">
    <link rel="stylesheet" href="/edit/css/text.css?version=<?=Text::h(G::$editor->version)?>">
    <link rel="stylesheet" href="/edit/css/galaxiaPublic.css?version=<?=Text::h(G::$editor->version)?>">

    <link rel="stylesheet" href="/edit/css/forms.css?version=<?=Text::h(G::$editor->version)?>">
</head>
<body>

<div class="paper">
    <img class="icon-big" src="/favicon.ico" alt="Icon">
    <a href="/" class="paper-header"><?=G::$req->host?></a>
<?php
    include G::$editor->dirView . G::$editor->view . '.phtml';
?>
</div>

<div id="footer">
    <p><img class="icon" alt="Icon" src="/edit/favicon.ico?version=<?=Text::h(G::$editor->version)?>">GalaxiaEditor</p>
    <p><a href="https://setastart.com/" target="_blank"> <img class="icon" alt="Setastart Icon" src="/edit/gfx/icon-setastart-white-32.png"/>setastart.com</a> &copy; 2017-<?=date("Y")?></p>
</div>

<script type="text/javascript">
window.addEventListener("DOMContentLoaded", function(event) {
    var iOS = !!navigator.platform && /iPad|iPhone|iPod/.test(navigator.platform);
    var safari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
    if (iOS && safari) document.querySelector('meta[name=viewport]').setAttribute('content', 'width=device-width, initial-scale=1.0, maximum-scale=1.0');
});
</script>

</body>
</html>
<?php   Flash::cleanMessages(); ?>
