<?php
// Copyright 2017-2022 Ino Detelić & Zaloa G. Ramos (setastart.com)
// Licensed under the European Union Public License, version 1.2 (EUPL-1.2)
// You may not use this work except in compliance with the Licence.
// Licence copy: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12

use Galaxia\Flash;
use Galaxia\G;
use Galaxia\Text;
use GalaxiaEditor\frag\FragMenu;
use GalaxiaEditor\frag\FragMsgBoxes;


// @formatter:off
?>
<!DOCTYPE html>
<html lang="<?=Text::h(G::lang())?>">
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <title>Error <?=Text::h(G::$errorCode)?></title>

    <link rel="shortcut icon" href="/edit/favicon.ico?version=<?=Text::h(G::$editor->version)?>">

    <link rel="stylesheet" href="/edit/css/reset.css?version=<?=Text::h(G::$editor->version)?>">
    <link rel="stylesheet" href="/edit/css/text.css?version=<?=Text::h(G::$editor->version)?>">
    <link rel="stylesheet" href="/edit/css/galaxiaEditor.css?version=<?=Text::h(G::$editor->version)?>">
    <link rel="stylesheet" href="/edit/css/forms.css?version=<?=Text::h(G::$editor->version)?>">
    <link rel="stylesheet" href="/edit/css/filters.css?version=<?=Text::h(G::$editor->version)?>">
    <link rel="stylesheet" href="/edit/css/responsive.css?version=<?=Text::h(G::$editor->version)?>">

    <script type="text/javascript" src="/edit/js/galaxiaEditor.js?version=<?=Text::h(G::$editor->version)?>"></script>
</head>
<body class="page-error">

<div id="openboxes">
</div>

<?php   FragMenu::render(); ?>

<div id="page">
<?php   FragMsgBoxes::render(); ?>
    <div class="paper pad">
        <div class="paper-header pad">
            <h1>Error <?=Text::h(G::$errorCode)?></h1>
        </div>
        <div class="pad">
            <?=nl2br(G::$error)?>
        </div>
<?php   if (G::isDevDebug()) { ?>
        <pre class="pad">
            <?php db(); ?>
        </pre>
<?php   } ?>
    </div>
</div>

<div id="footer">
    <div class="links">
        <a href="/edit/logout"><?=Text::t('Logout')?></a>
<?php   if (G::isDev()) { ?>
        <a href="/edit/dev" class="hide-perm-dev"><?=Text::t('🛠 Dev')?></a>
<?php   } ?>
        <a href="/edit/dev/cacheDeleteEditor"><?=Text::t('Delete Editor Caches')?></a>
    </div>
    <p class="version"><img class="icon" alt="Icon" src="/edit/favicon.ico"><?=Text::h(G::$me->name)?>@GalaxiaEditor v<?=Text::h(G::$editor->version);?></p>
    <p class="copy"><img class="icon" alt="Setastart Icon" src="/edit/gfx/icon/icon-setastart-white-32.png"/><a href="https://setastart.com/" target="_blank">setastart.com</a> &copy; 2017-<?=date("Y")?></p>
</div>

</body>
</html>
<?php   Flash::cleanMessages(); ?>
