<?=renderForm('', 'image-list', 'paper pad');?>

    <div class="paper-header pad">
        <h1><span class="rowsFiltered"><?=h($rowsFiltered)?></span> &#8725; <span class="rowsTotal"><?=h($rowsTotal)?></span> <?=t($pgTitle);?></h1>

<?php   if (!empty($geConf[$pgSlug]['gcImageList']['gcLinks'])) { ?>
        <div class="list-actions">
<?php   foreach ($geConf[$pgSlug]['gcImageList']['gcLinks'] as $href => $link) { ?>
            <a href="/edit/<?=h($pgSlug)?>/<?=h($href)?>" class="btn btn-pad <?=h($link['cssClass'])?>"><?=sprintf(t('+ Add new %s'), t('Image'))?></a>
<?php   } ?>
        </div>
<?php   } ?>
<?php   if (in_array('dev', $me->perms)) { ?>
        <div class="paper-header-links">
            <a href="/edit/dev/imageListDeleteResizes" class="hide-perm-dev btn-a"><?=t('Delete Resizes')?></a>
            <a href="/edit/dev/imageListReorder" class="btn-a"><?=t('Reorder Images')?></a>
        </div>
<?php   } ?>
    </div>




    <div class="filters filters-list">
<?php   if (!empty($filterTexts)) { ?>
<?php       foreach ($filterTexts as $filterId => $filter) { ?>
        <div class="input-wrap pad">
            <div class="input-label"><?=t($filter['label'])?></div>
<?php           if (empty($filter['filterEmpty'])) { ?>
            <input oninput="filter(this, event)" name="filterTexts[<?=$filterId?>]" class="input-text input-filter-text input-search br" type="search" value="<?=h($_POST['filterTexts'][$filterId] ?? '')?>">
<?php           } else { ?>
            <input oninput="filter(this, event)" name="filterTexts[<?=$filterId?>]" class="input-text input-filter-text input-search rl" type="search" value="<?=h($_POST['filterTexts'][$filterId] ?? '')?>">
            <label for="<?=h($filterId)?>-empty" class="btn btn-pill btn-checkbox rr">
                <?=t('Empty')?>
                <input onchange="filterEmpty(this, event)" type="checkbox" name="filterTexts[<?=$filterId?>]" value="{{empty}}" id="<?=h($filterId)?>-empty" title="<?=t('Empty')?>">
            </label>
<?php           } ?>
<?php           if ($filterId == 'type') { ?>
            <p class="small"><?=implode(', ', array_map('t', array_filter($geConf[$pgSlug]['gcImageTypes'])))?></p>
<?php           } ?>
        </div>
<?php       } ?>
<?php   } ?>

<?php   if (!empty($filterInts)) { ?>
<?php       foreach ($filterInts as $filterId => $filter) { ?>
        <div class="input-wrap input-filter-int pad">
            <div class="input-label"><?=t($filter['label'])?></div>
<?php       foreach ($filter['options'] as $key => $options) { ?>
            <label for="<?=h($filterId)?>-<?=h($key)?>" class="btn btn-pill btn-checkbox <?=h($options['cssClass'])?><?=($options['checked']) ? ' active' : ''?>">
                <?=t($options['label'])?>
                <input onchange="filter(this, event)" name="filterInts[<?=$filterId?>][<?=h($key)?>]" type="checkbox" value="1" id="<?=h($filterId)?>-<?=h($key)?>" title="<?=t($options['label'])?>" <?=($options['checked']) ? ' checked' : ''?>>
            </label>
<?php       } ?>
        </div>
<?php       } ?>
<?php   } ?>
    </div>


<?php   if ($pagination->active) { ?>
    <div class="pagination btn-row pad">
        <label class="input-label" for="itemsPerPage"><?=t('Per page')?></label>
        <div class="btn-group space-rgt">
            <input oninput="filter(this, event)" class="itemsPerPage" id="itemsPerPage" type="number" min="1" name="itemsPerPage" value="<?=$pagination->itemsPerPage?>">
        </div>
        <label class="input-label" for="pageCurrent">
            <?=t('Page')?>
        </label>
        <div class="btn-group">
            <input oninput="filter(this, event)" class="pageCurrent" id="pageCurrent" type="number" min="1" name="page" value="<?=$pagination->pageCurrent?>">
        </div>
        <div class="space-rgt"> &nbsp;&#8725;&nbsp; <span class="pageLast"><?=$pagination->pageLast?></span></div>
        <div class="btn-group">
            <button onclick="filter(this, event)" name="page" value="<?=$pagination->pageFirst?>" class="pageFirst btn-new pagination-first active" <?=($pagination->pageFirst) ?: 'disabled'?>></button>
        </div>
        <div class="btn-group">
            <button onclick="filter(this, event)" name="page" value="<?=$pagination->pagePrev?>" class="pagePrev btn-new pagination-prev active" <?=($pagination->pagePrev) ?: 'disabled'?>></button>
        </div>
        <div class="btn-group">
            <button onclick="filter(this, event)" name="page" value="<?=$pagination->pageNext?>" class="pageNext btn-new pagination-next active" <?=($pagination->pageNext) ?: 'disabled'?>></button>
        </div>
        <div class="btn-group">
            <button onclick="filter(this, event)" name="page" value="<?=$pagination->pageLast?>" class="pageLast btn-new pagination-last active" <?=($pagination->pageCurrent < $pagination->pageLast) ?: 'disabled'?>></button>
        </div>
    </div>
<?php   } ?>


    <div class="load">
<?php   include $editor->dirView . 'imageList/results.phtml'; ?>
    </div>


<?php   if ($pagination->active) { ?>
    <div class="pagination btn-row pad">
        <div class="btn-group">
            <button onclick="filter(this, event)" name="page" value="<?=$pagination->pageFirst?>" class="pageFirst btn-new pagination-first active" <?=($pagination->pageFirst) ?: 'disabled'?>></button>
        </div>
        <div class="btn-group space-rgt">
            <button onclick="filter(this, event)" name="page" value="<?=$pagination->pagePrev?>" class="pagePrev btn-new pagination-prev active" <?=($pagination->pagePrev) ?: 'disabled'?>></button>
        </div>

        <div class="space-rgt"><?=t('Page')?>&nbsp;<span class="pageCurrent"><?=$pagination->pageCurrent?></span> &nbsp;&#8725;&nbsp; <span class="pageLast"><?=$pagination->pageLast?></span></div>

        <div class="btn-group">
            <button onclick="filter(this, event)" name="page" value="<?=$pagination->pageNext?>" class="pageNext btn-new pagination-next active" <?=($pagination->pageNext) ?: 'disabled'?>></button>
        </div>
        <div class="btn-group">
            <button onclick="filter(this, event)" name="page" value="<?=$pagination->pageLast?>" class="pageLast btn-new pagination-last active" <?=($pagination->pageCurrent < $pagination->pageLast) ?: 'disabled'?>></button>
        </div>
    </div>
<?php   } ?>

<?php renderFormEnd(); ?>
