<?php use GalaxiaEditor\input\InputRender;


InputRender::form('', 'image-new', 'image image-new paper pad'); ?>

    <div class="paper-header pad">
        <h1><?=h($pgTitle)?></h1>
    </div>

    <div class="item-row">
<?php   $firstTime = true; ?>
<?php   $prefixPrev = null; ?>
<?php   foreach ($inputs as $input) { ?>
<?php       if (!$firstTime && ($prefixPrev == null || !isset($input['prefix']) || $input['prefix'] !== $prefixPrev)) { ?>
    </div>

    <div class="item-row">
<?php       } ?>
<?php       echo InputRender::renderInput($app, $input); ?>
<?php       $firstTime = false; ?>
<?php       $prefixPrev = $input['prefix'] ?? ''; ?>
<?php   } ?>
    </div>

    <div class="paper-footer pad">
        <div class="item-info">
<?php   if (isset($item['gcInfo'])) { ?>
<?php       foreach ($item['gcInfo'] as $info) { ?>
            <p><?=t($info['label'])?>: <?=h($info['value'])?></p>
<?php       } ?>
<?php   } ?>
        </div>
        <div class="paper-footer-actions">
            <button class="btn btn-green active"><?=t('Save')?></button>
            <button class="btn btn-blue active" name="submitAndGoBack"><?=t('Save and go back')?></button>
            <button class="btn btn-blue active" name="submitAndAddMore"><?=t('Save and add more')?></button>
        </div>
    </div>

<?php   InputRender::renderFormEnd(); ?>
