<?php
global $editor;
global $geConf;
global $pgSlug;
global $me;
?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <title>Error <?=h($errorCode)?></title>

    <link rel="shortcut icon" href="/edit/favicon.ico?version=<?=h($editor->version)?>">

    <link rel="stylesheet" href="/edit/css/reset.css?version=<?=h($editor->version)?>">
    <link rel="stylesheet" href="/edit/css/text.css?version=<?=h($editor->version)?>">
    <link rel="stylesheet" href="/edit/css/galaxiaEditor.css?version=<?=h($editor->version)?>">
    <link rel="stylesheet" href="/edit/css/forms.css?version=<?=h($editor->version)?>">
    <link rel="stylesheet" href="/edit/css/filters.css?version=<?=h($editor->version)?>">
    <link rel="stylesheet" href="/edit/css/responsive.css?version=<?=h($editor->version)?>">

    <script type="text/javascript" src="/edit/js/galaxiaEditor.js?version=<?=h($editor->version)?>"></script>
</head>
<body class="page-error">

<div id="website-link">
    <a target="_blank" rel="noopener" href="/">
        <img src="/favicon.ico" class="thumb-mini">
        <span><?=h($_SERVER['SERVER_NAME'])?></span>
    </a>
</div>

<?php include 'menu.phtml'; ?>

<div id="page">
    <div class="paper pad">
        <div class="paper-header pad">
            <h1>Error <?=h($errorCode)?></h1>
        </div>
        <div class="pad">
            <?=h($error)?>
        </div>
    </div>
<?php include 'messageBoxes.phtml'; ?>
</div>

<div id="footer">
    <div class="links">
        <a href="/edit/logout"><?=t('Logout')?></a>
<?php if (in_array('dev', $me->perms)) { ?>
        <a href="/edit/dev" class="hide-perm-dev">Developer</a>
<?php } ?>
        <a href="/edit/dev/cacheDeleteEditor"><?=t('Delete Editor Caches')?></a>
    </div>
    <p class="version"><img class="icon" src="/edit/favicon.ico"><?=h($me->name)?>@galaxia v<?=h($editor->version);?></p>
    <p class="copy"><img class="icon" src="/edit/gfx/icon-setastart-white-32.png"/><a href="https://setastart.com/" target="_blank">setastart.com</a> &copy; 2017-<?=date("Y")?></p>
</div>

</body>
</html>
<?php cleanMessages(); ?>
